const categories = [
  { id:'all', icon:'✦', label:{en:'All services',zh:'全部服务',es:'Todos los servicios'}, query:'community assistance center' },
  { id:'food', icon:'🍎', label:{en:'Food',zh:'食品援助',es:'Alimentos'}, query:'food pantry soup kitchen free meals' },
  { id:'shelter', icon:'🏠', label:{en:'Shelter & housing',zh:'住所与住房',es:'Refugio y vivienda'}, query:'emergency shelter housing assistance' },
  { id:'health', icon:'❤', label:{en:'Health',zh:'医疗健康',es:'Salud'}, query:'community health center free clinic' },
  { id:'mental', icon:'☀', label:{en:'Mental health',zh:'心理健康',es:'Salud mental'}, query:'mental health crisis counseling' },
  { id:'legal', icon:'⚖', label:{en:'Legal aid',zh:'法律援助',es:'Ayuda legal'}, query:'free legal aid nonprofit' },
  { id:'benefits', icon:'✓', label:{en:'Benefits',zh:'政府福利',es:'Beneficios'}, query:'public benefits SNAP Medicaid assistance' },
  { id:'jobs', icon:'💼', label:{en:'Jobs',zh:'就业支持',es:'Empleo'}, query:'American Job Center workforce help' },
  { id:'transport', icon:'🚌', label:{en:'Transportation',zh:'交通援助',es:'Transporte'}, query:'transportation assistance social services' },
  { id:'family', icon:'👪', label:{en:'Family support',zh:'家庭支持',es:'Apoyo familiar'}, query:'family resource center childcare assistance' }
];

const H={
  call:{en:'Hours vary by local office. Call or check the website before visiting.',zh:'各地办公时间不同。前往前请致电或查看官网。',es:'Los horarios varían. Llame o consulte el sitio antes de ir.'},
  always:{en:'24 hours a day, 7 days a week',zh:'每周 7 天、每天 24 小时',es:'Las 24 horas, todos los días'},
  online:{en:'Online directory available at all times',zh:'在线目录全天可用',es:'Directorio en línea disponible siempre'},
  business:{en:'Typical local business hours; confirm with the location',zh:'通常为当地办公时间；请向具体机构确认',es:'Horario local habitual; confirme con la sede'}
};
const E={
  open:{en:'Open to anyone seeking information or referrals.',zh:'任何需要信息或转介的人均可使用。',es:'Disponible para cualquier persona que busque información.'},
  varies:{en:'Eligibility, availability, and documents vary by local program.',zh:'资格、名额和所需文件因当地项目而异。',es:'La elegibilidad, disponibilidad y documentos varían según el programa.'}
};

const resources = [
 {id:'211',category:'all',name:'211 Community Resource Line',description:{en:'Local referrals for food, housing, utilities, healthcare, transportation, and crisis support.',zh:'提供食品、住房、水电、医疗、交通及危机支持的本地转介。',es:'Referencias locales para alimentos, vivienda, servicios, salud, transporte y crisis.'},phone:'211',url:'https://www.211.org/',source:'211 / United Way',verified:'2026-07-27',hours:H.always,services:['food','shelter','health','mental','benefits','transport','family'],eligibility:E.open,access:{en:'Call 211 or search by ZIP code online.',zh:'拨打 211 或在网上按邮编搜索。',es:'Llame al 211 o busque por código postal.'},keywords:['utility','rent','eviction','diapers','clothing','emergency']},
 {id:'findhelp',category:'all',name:'Findhelp',description:{en:'Search free and reduced-cost programs by ZIP code across many service types.',zh:'按邮编搜索多种免费或低费用服务。',es:'Busque programas gratuitos o de bajo costo por código postal.'},url:'https://www.findhelp.org/',source:'Findhelp',verified:'2026-07-27',hours:H.online,services:['food','shelter','health','mental','legal','benefits','jobs','transport','family'],eligibility:E.varies,access:{en:'Enter a ZIP code, choose a service, then contact the provider.',zh:'输入邮编、选择服务并联系机构。',es:'Ingrese un código postal, elija un servicio y contacte al proveedor.'},keywords:['free','low cost','local','case management']},
 {id:'hud',category:'shelter',name:'HUD Find Shelter',description:{en:'Official locator for shelters, food pantries, health clinics, and clothing resources.',zh:'官方查找住所、食品站、诊所和衣物资源。',es:'Buscador oficial de refugios, alimentos, clínicas y ropa.'},url:'https://www.hud.gov/findshelter',source:'U.S. Department of Housing and Urban Development',verified:'2026-07-27',hours:H.online,services:['shelter','food','health','family'],eligibility:E.varies,access:{en:'Search by location and call the listed provider before traveling.',zh:'按地点搜索，并在前往前致电机构。',es:'Busque por ubicación y llame antes de viajar.'},keywords:['homeless','evicted','clothing','housing']},
 {id:'feeding-america',category:'food',name:'Feeding America Food Bank Locator',description:{en:'Find a regional food bank connecting people to pantries and meal programs.',zh:'查找地区食品银行及其食品站和供餐项目。',es:'Encuentre bancos de alimentos, despensas y programas de comidas.'},url:'https://www.feedingamerica.org/find-your-local-foodbank',source:'Feeding America',verified:'2026-07-27',hours:H.call,services:['food','family'],eligibility:E.varies,access:{en:'Use the locator, then call the local food bank for distribution times.',zh:'使用查询器后，致电当地食品银行确认发放时间。',es:'Use el buscador y llame para confirmar horarios.'},keywords:['hungry','pantry','groceries','meal']},
 {id:'usda-hunger',category:'food',name:'USDA National Hunger Hotline',description:{en:'Connects callers with emergency food providers, meal sites, and nutrition programs.',zh:'帮助联系紧急食品、供餐点和公共营养项目。',es:'Conecta con alimentos de emergencia, comidas y programas de nutrición.'},phone:'1-866-348-6479',url:'https://www.fns.usda.gov/national-hunger-hotline',source:'USDA',verified:'2026-07-27',hours:{en:'Monday–Friday, 7:00 a.m.–10:00 p.m. Eastern Time',zh:'周一至周五，美东时间上午 7:00 至晚上 10:00',es:'Lunes a viernes, 7:00 a.m.–10:00 p.m. hora del Este'},services:['food','benefits'],eligibility:E.open,access:{en:'Call the hotline or use the official website.',zh:'致电热线或使用官方网站。',es:'Llame o use el sitio oficial.'},keywords:['hungry','meal','snap','wic']},
 {id:'hrsa',category:'health',name:'HRSA Health Center Locator',description:{en:'Find community health centers offering primary, dental, behavioral, and sliding-fee care.',zh:'查找提供基础医疗、牙科、心理健康和浮动收费的社区诊所。',es:'Busque centros con atención primaria, dental, conductual y tarifas variables.'},url:'https://findahealthcenter.hrsa.gov/',source:'Health Resources and Services Administration',verified:'2026-07-27',hours:H.call,services:['health','mental','family'],eligibility:{en:'Health centers serve everyone; fees are adjusted based on income and family size.',zh:'医疗中心服务所有人；费用按收入和家庭规模调整。',es:'Atienden a todos; las tarifas se ajustan según ingresos y familia.'},access:{en:'Search by address or ZIP code and contact the center for an appointment.',zh:'按地址或邮编搜索并联系诊所预约。',es:'Busque por dirección o código postal y solicite una cita.'},keywords:['doctor','dentist','clinic','uninsured','medicine']},
 {id:'samhsa',category:'mental',name:'FindTreatment.gov',description:{en:'Confidential locator for mental health and substance-use treatment facilities.',zh:'保密查找心理健康和物质使用治疗机构。',es:'Buscador confidencial de tratamiento de salud mental y consumo.'},phone:'1-800-662-4357',url:'https://findtreatment.gov/',source:'SAMHSA',verified:'2026-07-27',hours:H.always,services:['mental','health'],eligibility:E.open,access:{en:'Search online or call the national helpline.',zh:'在线搜索或致电国家热线。',es:'Busque en línea o llame a la línea nacional.'},keywords:['addiction','rehab','counseling','therapy']},
 {id:'988',category:'mental',name:'988 Suicide & Crisis Lifeline',description:{en:'Immediate crisis support by call, text, or chat.',zh:'通过电话、短信或在线聊天获得即时危机支持。',es:'Apoyo inmediato por llamada, texto o chat.'},phone:'988',url:'https://988lifeline.org/',source:'988 Lifeline',verified:'2026-07-27',hours:H.always,services:['mental'],eligibility:E.open,access:{en:'Call or text 988; chat is available online.',zh:'拨打或短信 988；也可在线聊天。',es:'Llame o envíe 988; chat disponible en línea.'},keywords:['suicide','crisis','unsafe','panic']},
 {id:'lawhelp',category:'legal',name:'LawHelp.org',description:{en:'Find nonprofit civil legal aid by state for housing, family, benefits, and immigration.',zh:'按州查找住房、家庭、福利和移民等民事法律援助。',es:'Ayuda legal civil por estado para vivienda, familia, beneficios e inmigración.'},url:'https://www.lawhelp.org/',source:'LawHelp / Pro Bono Net',verified:'2026-07-27',hours:H.online,services:['legal','shelter','benefits','family'],eligibility:E.varies,access:{en:'Choose your state and legal topic, then contact the listed program.',zh:'选择州和法律问题后联系项目。',es:'Elija estado y tema, luego contacte al programa.'},keywords:['lawyer','immigration','eviction','divorce','court']},
 {id:'benefit-finder',category:'benefits',name:'USA.gov Benefit Finder',description:{en:'Official screening tool for federal and state benefit programs.',zh:'联邦和州福利项目的官方筛选工具。',es:'Herramienta oficial para beneficios federales y estatales.'},url:'https://www.usa.gov/benefit-finder',source:'USA.gov',verified:'2026-07-27',hours:H.online,services:['benefits','food','health','family'],eligibility:E.varies,access:{en:'Complete the questionnaire and follow official application links.',zh:'完成问卷并使用官方申请链接。',es:'Complete el cuestionario y siga los enlaces oficiales.'},keywords:['medicaid','ssi','disability','unemployment','cash']},
 {id:'snap',category:'benefits',name:'SNAP State Directory',description:{en:'Find your state SNAP agency, application, and contact information.',zh:'查找所在州的 SNAP 机构、申请和联系方式。',es:'Encuentre la agencia SNAP estatal y cómo solicitar.'},url:'https://www.fns.usda.gov/snap/state-directory',source:'USDA Food and Nutrition Service',verified:'2026-07-27',hours:H.business,services:['benefits','food','family'],eligibility:E.varies,access:{en:'Select your state to apply online or contact the local office.',zh:'选择所在州在线申请或联系当地办公室。',es:'Seleccione su estado para solicitar o contactar una oficina.'},keywords:['ebt','food stamps','wic']},
 {id:'job-centers',category:'jobs',name:'American Job Center Finder',description:{en:'Free employment, résumé, training, unemployment, and career services.',zh:'免费就业、简历、培训、失业和职业服务。',es:'Servicios gratuitos de empleo, currículum, capacitación y carrera.'},url:'https://www.careeronestop.org/LocalHelp/AmericanJobCenters/american-job-centers.aspx',source:'U.S. Department of Labor / CareerOneStop',verified:'2026-07-27',hours:H.business,services:['jobs','benefits'],eligibility:E.open,access:{en:'Search by ZIP code and contact the center for current schedules.',zh:'按邮编搜索并联系中心确认时间。',es:'Busque por código postal y confirme horarios.'},keywords:['work','resume','training','unemployed']},
 {id:'community-action',category:'family',name:'Community Action Agency Locator',description:{en:'Local organizations offering utility help, housing stability, weatherization, Head Start, and family support.',zh:'提供水电、住房稳定、节能改造、启蒙教育和家庭支持的本地机构。',es:'Agencias locales para servicios, vivienda, climatización, Head Start y familias.'},url:'https://communityactionpartnership.com/find-a-cap/',source:'Community Action Partnership',verified:'2026-07-27',hours:H.business,services:['family','benefits','shelter','jobs','transport'],eligibility:E.varies,access:{en:'Use the locator and contact the agency serving your county.',zh:'使用查询器并联系服务所在县的机构。',es:'Use el buscador y contacte la agencia de su condado.'},keywords:['utility','rent','childcare','head start','weatherization']},
 {id:'salvation-army',category:'all',name:'The Salvation Army Service Locator',description:{en:'Local centers may provide meals, shelter, rent or utility help, disaster aid, and family services.',zh:'本地中心可能提供餐食、住所、房租水电、灾害和家庭援助。',es:'Centros locales pueden ofrecer comidas, refugio, renta, servicios y ayuda familiar.'},url:'https://www.salvationarmyusa.org/usn/plugins/gdosCenterSearch?start=1',source:'The Salvation Army',verified:'2026-07-27',hours:H.call,services:['food','shelter','benefits','family'],eligibility:E.varies,access:{en:'Search by ZIP code and call the local center before visiting.',zh:'按邮编搜索并在前往前致电当地中心。',es:'Busque por código postal y llame antes de ir.'},keywords:['clothing','disaster','rent','utility']},
 {id:'catholic-charities',category:'all',name:'Catholic Charities Agency Locator',description:{en:'Local agencies may offer food, housing, immigration legal services, disaster support, and case management.',zh:'本地机构可能提供食品、住房、移民法律、灾害援助和个案管理。',es:'Agencias locales pueden ofrecer alimentos, vivienda, inmigración, desastres y gestión de casos.'},url:'https://www.catholiccharitiesusa.org/find-help/',source:'Catholic Charities USA',verified:'2026-07-27',hours:H.call,services:['food','shelter','legal','family','benefits'],eligibility:E.varies,access:{en:'Find the nearest agency and contact it for current programs.',zh:'查找最近机构并联系确认当前项目。',es:'Encuentre la agencia más cercana y confirme programas.'},keywords:['immigration','refugee','case management','rent']}
];

const keywordMap={
 food:['food','hungry','hunger','meal','pantry','groceries','eat','comida','alimento','hambre','食品','食物','饿','吃饭'],
 shelter:['shelter','housing','homeless','evicted','eviction','rent','motel','sleep','refugio','vivienda','desalojo','住所','住房','无家可归','房租','驱逐'],
 health:['health','clinic','doctor','dental','dentist','medicine','uninsured','hospital','salud','médico','clínica','医疗','诊所','医生','药'],
 mental:['mental','crisis','suicide','therapy','counseling','addiction','rehab','depressed','anxiety','salud mental','心理','危机','自杀','焦虑','抑郁','戒毒'],
 legal:['legal','lawyer','court','immigration','divorce','custody','abogado','inmigración','法律','律师','移民','法院'],
 benefits:['benefits','snap','ebt','medicaid','ssi','disability','unemployment','wic','utility','bill','beneficios','福利','失业金','残障','水电'],
 jobs:['job','work','resume','career','training','employment','empleo','trabajo','工作','就业','简历','培训'],
 transport:['transport','ride','bus','gas','car','transporte','交通','乘车','公交'],
 family:['family','childcare','diaper','baby','senior','veteran','head start','familia','家庭','托儿','尿布','老人','退伍军人']
};


const I18N={
 en:{home:'Home',find:'Find help',saved:'Saved',about:'About',tagline:'Trusted help, clearer next steps.',hero:'Find help near you today.',sub:'Describe what you need and enter a city or ZIP code. BridgeAid will identify relevant services and connect you to trusted national and local search tools.',need:'What do you need?',needPh:'Example: food today, shelter tonight, rent help',location:'City, state, or ZIP code',search:'Search resources',gps:'Use my location',popular:'Popular services',results:'Search results',recommended:'Recommended directories',nearby:'Live nearby searches',filters:'Filter results',all:'All',hours:'Hours',services:'Services',eligibility:'Eligibility',next:'How to access',source:'Source',verified:'Last checked',open:'Open official site',call:'Call',directions:'Search nearby',save:'Save',savedLabel:'Saved',noResults:'No direct match found. Try broader wording or select a service category.',locationNeeded:'Add a city or ZIP code to search nearby centers.',queryNeeded:'Describe what help you need or choose a category.',emergency:'Emergency: call 911',crisis:'Crisis support: call or text 988',community:'Community help: call 211',disclaimer:'Hours, eligibility, and availability can change. Call or check the official site before traveling.',savedEmpty:'No saved resources yet.',clear:'Clear search',sort:'Sort',relevance:'Most relevant',name:'Name',aboutTitle:'How BridgeAid works',aboutText:'BridgeAid is a privacy-first navigation tool. It matches your words to service categories, ranks trusted directories, and creates live local searches. It does not determine eligibility or guarantee availability.',privacy:'Your search, language, location, and saved items stay in this browser.',live:'Live search',openMaps:'Open map results',searchingFor:'Searching for',in:'near',found:'resources matched',menu:'Menu'},
 zh:{home:'首页',find:'寻找帮助',saved:'已保存',about:'关于',tagline:'可信帮助，更清晰的下一步。',hero:'查找今天附近可用的帮助。',sub:'描述您的需求并输入城市或邮编。BridgeAid 会识别相关服务，并连接可信的全国目录和本地实时搜索。',need:'您需要什么帮助？',needPh:'例如：今天需要食品、今晚需要住所、房租援助',location:'城市、州或邮编',search:'搜索资源',gps:'使用我的位置',popular:'常用服务',results:'搜索结果',recommended:'推荐目录',nearby:'附近实时搜索',filters:'筛选结果',all:'全部',hours:'开放时间',services:'服务内容',eligibility:'资格要求',next:'如何获得服务',source:'来源',verified:'最后核实',open:'打开官方网站',call:'致电',directions:'搜索附近机构',save:'保存',savedLabel:'已保存',noResults:'没有找到直接匹配。请尝试更宽泛的描述或选择服务类别。',locationNeeded:'请输入城市或邮编以搜索附近机构。',queryNeeded:'请描述您需要的帮助，或选择一个服务类别。',emergency:'紧急情况：拨打 911',crisis:'危机支持：拨打或短信 988',community:'社区帮助：拨打 211',disclaimer:'开放时间、资格和名额可能变化。前往前请致电或查看官方网站。',savedEmpty:'还没有保存资源。',clear:'清除搜索',sort:'排序',relevance:'最相关',name:'名称',aboutTitle:'BridgeAid 如何工作',aboutText:'BridgeAid 是一个重视隐私的导航工具。它根据您的描述匹配服务类别、排序可信目录并生成本地实时搜索。它不能决定资格或保证名额。',privacy:'您的搜索、语言、地点和收藏仅保存在本浏览器中。',live:'实时搜索',openMaps:'打开地图结果',searchingFor:'正在搜索',in:'地点',found:'个匹配资源',menu:'菜单'},
 es:{home:'Inicio',find:'Buscar ayuda',saved:'Guardados',about:'Acerca de',tagline:'Ayuda confiable y próximos pasos claros.',hero:'Encuentre ayuda cerca de usted hoy.',sub:'Describa lo que necesita e ingrese una ciudad o código postal. BridgeAid identifica servicios y conecta con directorios confiables y búsquedas locales.',need:'¿Qué ayuda necesita?',needPh:'Ejemplo: comida hoy, refugio esta noche, ayuda con renta',location:'Ciudad, estado o código postal',search:'Buscar recursos',gps:'Usar mi ubicación',popular:'Servicios populares',results:'Resultados',recommended:'Directorios recomendados',nearby:'Búsquedas cercanas en vivo',filters:'Filtrar resultados',all:'Todo',hours:'Horario',services:'Servicios',eligibility:'Elegibilidad',next:'Cómo acceder',source:'Fuente',verified:'Última revisión',open:'Abrir sitio oficial',call:'Llamar',directions:'Buscar cerca',save:'Guardar',savedLabel:'Guardado',noResults:'No se encontró una coincidencia directa. Pruebe palabras más amplias o elija una categoría.',locationNeeded:'Agregue ciudad o código postal para buscar centros cercanos.',queryNeeded:'Describa la ayuda que necesita o elija una categoría.',emergency:'Emergencia: llame al 911',crisis:'Crisis: llame o envíe texto al 988',community:'Ayuda comunitaria: llame al 211',disclaimer:'Horarios, elegibilidad y disponibilidad pueden cambiar. Llame o consulte el sitio antes de ir.',savedEmpty:'Aún no hay recursos guardados.',clear:'Limpiar búsqueda',sort:'Ordenar',relevance:'Más relevante',name:'Nombre',aboutTitle:'Cómo funciona BridgeAid',aboutText:'BridgeAid es una herramienta privada de navegación. Relaciona sus palabras con categorías, ordena directorios confiables y crea búsquedas locales en vivo. No decide elegibilidad ni garantiza cupos.',privacy:'Su búsqueda, idioma, ubicación y guardados permanecen en este navegador.',live:'Búsqueda en vivo',openMaps:'Abrir resultados del mapa',searchingFor:'Buscando',in:'cerca de',found:'recursos encontrados',menu:'Menú'}
};
const $=s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const load=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
const state={lang:load('ba-lang','en'),page:load('ba-page','home'),query:load('ba-query',''),location:load('ba-location',''),category:load('ba-category','all'),sort:'relevance',saved:new Set(load('ba-saved',[])),coords:load('ba-coords',null)};
const app=$('#app');
const t=k=>I18N[state.lang][k]||I18N.en[k]||k;
const tx=o=>o?.[state.lang]||o?.en||'';
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const persist=()=>{localStorage.setItem('ba-lang',JSON.stringify(state.lang));localStorage.setItem('ba-page',JSON.stringify(state.page));localStorage.setItem('ba-query',JSON.stringify(state.query));localStorage.setItem('ba-location',JSON.stringify(state.location));localStorage.setItem('ba-category',JSON.stringify(state.category));localStorage.setItem('ba-saved',JSON.stringify([...state.saved]));localStorage.setItem('ba-coords',JSON.stringify(state.coords));};
const cat=id=>categories.find(c=>c.id===id)||categories[0];
function detectCategories(q){const s=q.toLowerCase();return Object.entries(keywordMap).filter(([,words])=>words.some(w=>s.includes(w))).map(([id])=>id)}
function score(r){const q=state.query.toLowerCase().trim();const detected=detectCategories(q);let n=0;if(state.category!=='all'&&(r.category===state.category||r.services.includes(state.category)))n+=30;if(detected.some(c=>r.category===c||r.services.includes(c)))n+=35;const hay=[r.name,tx(r.description),...r.keywords,...r.services].join(' ').toLowerCase();q.split(/\s+/).filter(x=>x.length>1).forEach(w=>{if(hay.includes(w))n+=6});if(r.category==='all')n+=4;return n}
function filtered(){let arr=resources.map(r=>({...r,_score:score(r)}));const active=state.query.trim()||state.category!=='all';if(active)arr=arr.filter(r=>r._score>0);if(state.sort==='name')arr.sort((a,b)=>a.name.localeCompare(b.name));else arr.sort((a,b)=>b._score-a._score||a.name.localeCompare(b.name));return arr}
function mapsUrl(query){const near=state.location||state.coords&&`${state.coords.lat},${state.coords.lng}`||'';return `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(query+(near?` near ${near}`:''))}`}
function nav(){return `<header class="topbar"><nav class="wrap nav"><button class="brand" data-page="home"><span class="logo">B</span><span>BridgeAid<small>${t('tagline')}</small></span></button><button class="mobile-menu" id="menu" aria-label="${t('menu')}">☰</button><div class="nav-links" id="navLinks"><button data-page="home">${t('home')}</button><button data-page="find">${t('find')}</button><button data-page="saved">${t('saved')} (${state.saved.size})</button><button data-page="about">${t('about')}</button></div><div class="nav-actions"><select id="language" aria-label="Language"><option value="en">English</option><option value="zh">中文</option><option value="es">Español</option></select><a class="small-btn" href="tel:211">☎ 211</a></div></nav></header>`}
function safety(){return `<div class="safety"><a href="tel:911">${t('emergency')}</a><a href="tel:988">${t('crisis')}</a><a href="tel:211">${t('community')}</a></div>`}
function searchBox(compact=false){return `<form id="searchForm" class="search-box ${compact?'compact':''}"><label><span>${t('need')}</span><input id="needInput" value="${esc(state.query)}" placeholder="${t('needPh')}" autocomplete="off"></label><label><span>${t('location')}</span><input id="locationInput" value="${esc(state.location)}" placeholder="${t('location')}" autocomplete="postal-code"></label><button type="button" class="secondary" id="gps">◎ ${t('gps')}</button><button class="primary" type="submit">⌕ ${t('search')}</button></form>`}
function categoryButtons(){return `<div class="category-grid">${categories.filter(c=>c.id!=='all').map(c=>`<button class="category" data-category="${c.id}"><span>${c.icon}</span><strong>${tx(c.label)}</strong></button>`).join('')}</div>`}
function card(r){const saved=state.saved.has(r.id);return `<article class="resource-card"><div class="card-top"><span class="tag">${cat(r.category).icon} ${tx(cat(r.category).label)}</span><button class="save-btn" data-save="${r.id}" aria-pressed="${saved}">${saved?'★ '+t('savedLabel'):'☆ '+t('save')}</button></div><h3>${esc(r.name)}</h3><p class="description">${esc(tx(r.description))}</p><details><summary>${t('hours')} · ${t('services')} · ${t('eligibility')}</summary><dl><dt>${t('hours')}</dt><dd>${esc(tx(r.hours))}</dd><dt>${t('services')}</dt><dd>${r.services.map(s=>esc(tx(cat(s).label))).join(' · ')}</dd><dt>${t('eligibility')}</dt><dd>${esc(tx(r.eligibility))}</dd><dt>${t('next')}</dt><dd>${esc(tx(r.access))}</dd></dl></details><div class="facts"><span>${t('source')}: ${esc(r.source)}</span><span>${t('verified')}: ${esc(r.verified)}</span></div><div class="card-actions"><a class="primary" target="_blank" rel="noopener" href="${r.url}">${t('open')} ↗</a>${r.phone?`<a class="secondary" href="tel:${r.phone.replace(/[^\d+]/g,'')}">☎ ${t('call')}</a>`:''}<a class="ghost" target="_blank" rel="noopener" href="${mapsUrl(`${r.name} ${cat(r.category).query}`)}">⌖ ${t('directions')}</a></div></article>`}
function liveSearches(){if(!state.location&&!state.coords)return `<div class="notice">${t('locationNeeded')}</div>`;const ids=state.category!=='all'?[state.category]:detectCategories(state.query);const list=(ids.length?ids:['food','shelter','health','legal']).slice(0,4);return `<div class="live-grid">${list.map(id=>{const c=cat(id);return `<a class="live-card" target="_blank" rel="noopener" href="${mapsUrl(c.query)}"><span>${c.icon}</span><div><strong>${tx(c.label)}</strong><small>${t('live')} · ${state.location||'GPS'}</small></div><b>↗</b></a>`}).join('')}</div>`}
function home(){return `<main id="main"><section class="hero"><div class="wrap"><span class="eyebrow">BridgeAid</span><h1>${t('hero')}</h1><p>${t('sub')}</p>${searchBox()}${safety()}</div></section><section class="wrap section"><div class="section-head"><h2>${t('popular')}</h2></div>${categoryButtons()}</section><section class="wrap section"><div class="section-head"><h2>${t('recommended')}</h2><button class="text-btn" data-page="find">${t('find')} →</button></div><div class="resource-list">${resources.slice(0,4).map(card).join('')}</div></section></main>`}
function find(){const arr=filtered();const detected=detectCategories(state.query);return `<main id="main" class="wrap section page"><div class="page-head"><div><span class="eyebrow">${t('searchingFor')}</span><h1>${t('results')}</h1><p>${state.query?`“${esc(state.query)}”`:t('queryNeeded')} ${state.location?` · ${t('in')} ${esc(state.location)}`:''}</p></div>${safety()}</div>${searchBox(true)}<div class="toolbar"><div class="pills">${categories.map(c=>`<button class="pill ${state.category===c.id?'active':''}" data-category="${c.id}">${c.icon} ${tx(c.label)}</button>`).join('')}</div><label class="sort">${t('sort')}<select id="sort"><option value="relevance">${t('relevance')}</option><option value="name">${t('name')}</option></select></label></div>${detected.length?`<div class="intent">${detected.map(id=>`${cat(id).icon} ${tx(cat(id).label)}`).join(' · ')}</div>`:''}<section><div class="section-head"><h2>${t('recommended')} <small>${arr.length} ${t('found')}</small></h2><button class="text-btn" id="clear">${t('clear')}</button></div><div class="resource-list">${arr.length?arr.map(card).join(''):`<div class="empty">${t('noResults')}</div>`}</div></section><section class="section"><div class="section-head"><h2>${t('nearby')}</h2></div>${liveSearches()}</section><p class="disclaimer">${t('disclaimer')}</p></main>`}
function savedPage(){const arr=resources.filter(r=>state.saved.has(r.id));return `<main id="main" class="wrap section page"><div class="page-head"><h1>${t('saved')}</h1>${safety()}</div><div class="resource-list">${arr.length?arr.map(card).join(''):`<div class="empty">${t('savedEmpty')}</div>`}</div></main>`}
function about(){return `<main id="main" class="wrap section page about"><span class="eyebrow">BridgeAid</span><h1>${t('aboutTitle')}</h1><p class="lead">${t('aboutText')}</p><div class="about-grid"><article><h2>1</h2><p>${t('need')}</p></article><article><h2>2</h2><p>${t('recommended')}</p></article><article><h2>3</h2><p>${t('nearby')}</p></article></div><div class="notice">${t('privacy')}</div>${safety()}</main>`}
function render(){document.documentElement.lang=state.lang==='zh'?'zh-Hans':state.lang;app.innerHTML=nav()+(state.page==='home'?home():state.page==='find'?find():state.page==='saved'?savedPage():about())+`<footer><div class="wrap">BridgeAid · ${new Date().getFullYear()}<br><small>${t('disclaimer')}</small></div></footer>`;bind()}
function bind(){const lang=$('#language');lang.value=state.lang;lang.onchange=e=>{state.lang=e.target.value;persist();render()};$('#menu')?.addEventListener('click',()=>$('#navLinks').classList.toggle('open'));$$('[data-page]').forEach(b=>b.onclick=()=>{state.page=b.dataset.page;persist();render();scrollTo(0,0)});$$('[data-category]').forEach(b=>b.onclick=()=>{state.category=b.dataset.category;state.page='find';if(!state.query)state.query=tx(cat(state.category).label);persist();render();scrollTo(0,0)});$$('[data-save]').forEach(b=>b.onclick=()=>{state.saved.has(b.dataset.save)?state.saved.delete(b.dataset.save):state.saved.add(b.dataset.save);persist();render()});$('#searchForm')?.addEventListener('submit',e=>{e.preventDefault();state.query=$('#needInput').value.trim();state.location=$('#locationInput').value.trim();const detected=detectCategories(state.query);state.category=detected.length===1?detected[0]:'all';state.page='find';persist();render();scrollTo(0,0)});$('#gps')?.addEventListener('click',()=>{if(!navigator.geolocation){alert(t('locationNeeded'));return}navigator.geolocation.getCurrentPosition(p=>{state.coords={lat:p.coords.latitude.toFixed(5),lng:p.coords.longitude.toFixed(5)};state.location=`${state.coords.lat}, ${state.coords.lng}`;persist();render()},()=>alert(t('locationNeeded')))});$('#sort')&&(($('#sort').value=state.sort),$('#sort').onchange=e=>{state.sort=e.target.value;render()});$('#clear')?.addEventListener('click',()=>{state.query='';state.category='all';persist();render()})}
render();
if('serviceWorker' in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./service-worker.js').catch(()=>{});
