export const SUPPORTED_LANGUAGES = ['en', 'zh', 'es'];

export const LOCALES = {
  en: {
    brandTagline: 'Trusted help. Clear next steps.',
    appTitle: 'BridgeAid — trusted community help',
    mainNavigation: 'Main navigation',
    openMenu: 'Open menu',
    navHome: 'Home',
    navFind: 'Local Help',
    navNationwide: 'Nationwide Help',
    navEligibility: 'Eligibility',
    navSaved: 'Saved',
    navPrivacy: 'Privacy',
    language: 'Language',
    modeSelf: 'I need help',
    modeHelper: 'I’m helping someone',
    switchMode: 'Switch how you are using BridgeAid',
    modeQuestion: 'How are you using BridgeAid?',
    modeSelfDescription: 'Find food, shelter, health care, and other support for yourself.',
    modeHelperDescription: 'Find and organize resources for another person.',
    cancel: 'Cancel',
    selfEyebrow: 'Help near you',
    selfHero: 'What do you need right now?',
    selfSub: 'Find free help near you.',
    helperEyebrow: 'Helper workspace',
    helperHero: 'Help someone find support.',
    helperSub: 'Answer a few questions to build a resource plan.',
    needLabel: 'What kind of help do you need?',
    needChoose: 'Choose a type of help',
    needOther: 'Other',
    needOtherLabel: 'Describe the help you need',
    needOtherPlaceholder: 'Example: internet access or clothing',
    chooseNeed: 'Choose an immediate need',
    situationLabel: 'Describe the exact situation',
    situationPlaceholder: 'Example: I need food tonight and do not have identification.',
    required: 'Required',
    locationSuggestionsLoading: 'Finding U.S. locations…',
    notYetVerified: 'Not yet verified; discovered {date}',
    discoveryRunning: 'This location is searchable. Verified results are shown now while additional discovery continues.',
    loadMore: 'Load more ({remaining} remaining)',
    savedNeedsVerification: '{count} saved item(s) are hidden because current information is not verified.',
    retryVerification: 'Retry verification',
    multipleMethods: 'Multiple methods available',
    categoryAll: 'All Services',
    categoryFood: 'Food',
    categoryShelter: 'Housing and Shelter',
    categorySafe: 'Safe place',
    categoryHealth: 'Healthcare',
    categoryMental: 'Mental Health',
    categoryHygiene: 'Clothing and Hygiene',
    categoryTransport: 'Transportation',
    categoryBenefits: 'Financial Assistance and Benefits',
    categoryJobs: 'Employment',
    categoryEducation: 'Education and Scholarships',
    categoryLegal: 'Legal Assistance',
    categoryFamily: 'Childcare and Family Support',
    categoryDisability: 'Disability Services',
    categoryVeteran: 'Veteran Services',
    categoryImmigration: 'Immigration Assistance',
    categoryInternet: 'Internet and Technology',
    locationLabel: 'City, ZIP code, county, neighborhood, address, or landmark',
    locationPlaceholder: 'Example: 98101 or Seattle, WA',
    locationPrivacy: 'A general location is enough. Exact GPS coordinates are not saved.',
    distanceUnit: 'Distance unit',
    miles: 'Miles',
    kilometers: 'Kilometers',
    radius: 'Search radius',
    radiusMiles: '{value,plural,mile,miles}',
    radiusKilometers: '{value} km',
    travelMode: 'Directions',
    walking: 'Walking',
    transit: 'Transit',
    driving: 'Driving',
    useLocation: 'Use my location',
    findResources: 'Find resources',
    communitySupport: 'Community resources',
    call211: 'Call 211',
    call211Tooltip: 'Call 211 for free, confidential local resource referrals.',
    safetySupportNote: 'BridgeAid is a resource directory. If someone is in immediate danger, contact local emergency services.',
    noHomeResources: 'Choose a need and location to see verified resources.',
    searchResults: 'Resource results',
    resultsFor: 'Results for {need} near {location}',
    resultsCount: '{count} resources',
    everyResultSourced: 'Every result includes a traceable source.',
    loading: 'Checking saved resources and current sources…',
    offline: 'You are offline. Only resources still within their verification period are available.',
    cached: 'Showing recently verified results.',
    refreshed: 'Current results were verified.',
    stale: 'Outdated saved results were hidden and queued for re-verification.',
    searchError: 'Current resource information could not be verified.',
    searchUnavailable: 'Current resource information could not be verified. Outdated saved results are not shown.',
    searchPartialResults: 'Verified saved resources are shown. Live discovery could not be refreshed, so confirm time-sensitive details.',
    retrySearch: 'Retry',
    locationRequired: 'Choose a need and enter a location to search.',
    locationAmbiguous: 'More than one location matched. Add a state or ZIP code.',
    locationNotFound: 'Location not found. Check the spelling or add a state or ZIP code.',
    locationSuggestions: 'Did you mean one of these locations?',
    locationDenied: 'Location permission was not granted. Enter a city or ZIP code instead.',
    locationTimeout: 'Location request timed out. Enter a city or ZIP code instead.',
    storageBlocked: 'Your browser blocked local saving. This session still works, but changes may not persist.',
    filters: 'Filter these results',
    filterOpenNow: 'Open now',
    filterAvailableToday: 'Available today',
    filterWalkIn: 'Walk-ins accepted',
    filterNoId: 'No identification required',
    filterNoRegistration: 'No registration required',
    filterAccessible: 'Wheelchair accessible',
    filterVerifiedEligibility: 'Locally verified eligibility',
    filterLanguage: 'Language offered',
    filterLanguagePlaceholder: 'Example: Spanish',
    clearFilters: 'Clear filters',
    noResults: 'No verified resources match these filters. Clear a filter or broaden the search.',
    sortBy: 'Sort by',
    sortNearest: 'Nearest',
    sortFarthest: 'Farthest',
    sortRelevant: 'Most relevant',
    sortOpenSoonest: 'Open soonest',
    category: 'Service category',
    address: 'Full address',
    addressUnavailable: 'Open the official directory to choose a local program and address.',
    distance: 'Walking distance',
    walkingEstimate: '{distance} · about {minutes} min walking',
    hours: 'Hours',
    typicalHours: 'Typical hours',
    schedule: 'Schedule',
    schedulePublished: 'Published schedule',
    scheduleUncertain: 'Schedule could not be verified',
    scheduleResearching: 'Checking official schedule sources',
    hoursNotPubliclyListed: 'Hours not publicly listed',
    appointmentOnly: 'Appointment only',
    onlineAvailable: 'Available online',
    open24Hours: 'Open 24 hours',
    temporaryClosure: 'Temporarily closed',
    opensAt: 'Opens at {time}',
    holidayHours: 'Holiday hours',
    specialHours: 'Special hours',
    hoursSource: 'Hours source',
    dayMonday: 'Monday',
    dayTuesday: 'Tuesday',
    dayWednesday: 'Wednesday',
    dayThursday: 'Thursday',
    dayFriday: 'Friday',
    daySaturday: 'Saturday',
    daySunday: 'Sunday',
    availability: 'Current availability',
    availabilityConfirm: 'Confirm before visiting',
    openNow: 'Open now',
    closed: 'Closed',
    openingSoon: 'Opening soon',
    availableToday: 'Available today',
    upcomingEvent: 'Upcoming event',
    verifiedPreviously: 'Previously checked; confirm time-sensitive details.',
    communitySourced: 'Community-sourced; confirm with the organization.',
    needsVerification: 'Needs confirmation.',
    eligibilitySummary: 'Eligibility',
    eligibilityLocalUnknown: 'Local eligibility rules could not be verified.',
    eligibilityNotPubliclyListed: 'This program does not publicly list specific eligibility requirements. Contact the provider for confirmation.',
    noEligibilityRequirementsListed: 'No eligibility requirements published',
    noEligibilityRequirementsExplanation: 'No eligibility requirements published. This provider does not publicly list specific restrictions, so contact the provider to confirm.',
    eligibilityTemporarilyUnavailable: 'Eligibility Information Temporarily Unavailable',
    eligibilityTemporarilyUnavailableExplanation: 'Current eligibility information could not be verified. Retry later or contact the provider before relying on this listing.',
    registrationRequirement: 'How to apply',
    officialWebsite: 'Official website',
    officialApplication: 'Official application',
    lastVerified: 'Last verified',
    verification: 'Verification',
    sources: 'Sources',
    sourceNumber: 'Source {number}',
    conflictingInfo: 'Conflicting information',
    aiSummary: 'BridgeAid summary',
    confirmOrganization: 'Confirm eligibility and availability with the organization.',
    call: 'Call',
    walkingDirections: 'Walking directions',
    transitDirections: 'Transit directions',
    drivingDirections: 'Driving directions',
    viewRequirements: 'View requirements',
    checkEligibility: 'Eligibility',
    registrationHelp: 'Get registration help',
    reportIncorrect: 'Report incorrect information',
    save: 'Save',
    savedAction: 'Saved',
    selectPlan: 'Select for plan',
    inPlan: 'In plan',
    compare: 'Compare',
    comparison: 'Compare resources',
    clearComparison: 'Clear comparison',
    compareResource: 'Resource',
    compareEligibility: 'Local eligibility',
    compareSource: 'Official source',
    close: 'Close',
    helperIntakeStep: 'Guided intake · required fields marked',
    helperIntakeTitle: 'What should the plan account for?',
    clearIntake: 'Clear intake',
    privacyNotice: 'Only enter information you have permission to use. Notes stay on this device.',
    sensitiveWarning: 'Do not enter names, identification numbers, banking information, passwords, or photos of documents.',
    optional: 'Optional',
    immediateNeed: 'Immediate need',
    safetyTonight: 'Safety tonight',
    safe: 'Safe',
    notSafe: 'Not safe',
    unsure: 'Unsure',
    ageGroup: 'Age group',
    children: 'Children involved',
    yes: 'Yes',
    no: 'No',
    veteranStatus: 'Veteran status',
    preferNot: 'Prefer not to say',
    identification: 'Identification available',
    someDocuments: 'Some documents',
    transportation: 'Transportation available',
    walkingOnly: 'Walking only',
    car: 'Car',
    needsRide: 'Needs a ride',
    phoneAccess: 'Phone access',
    reliable: 'Reliable',
    limited: 'Limited',
    noPhone: 'No phone',
    accessibilityNeeds: 'Accessibility needs',
    preferredLanguage: 'Preferred language',
    familyRestrictions: 'Family restrictions',
    petRestrictions: 'Pet restrictions',
    genderRestrictions: 'Gender restrictions',
    ageRestrictions: 'Age restrictions',
    sobrietyRestrictions: 'Sobriety restrictions',
    additionalNotes: 'Additional notes',
    localDeviceNote: 'Stored on this device',
    buildOptions: 'Build resource options',
    planLocal: 'Local plan · {count} selected',
    resourcePlan: 'Resource plan',
    need: 'Need',
    location: 'Location',
    notEntered: 'Not entered',
    created: 'Created',
    updated: 'Updated',
    planEmpty: 'Select resources to build a plan. Notes and status stay on this device.',
    status: 'Status',
    statusNotContacted: 'Not contacted',
    statusCalled: 'Called',
    statusConfirmed: 'Confirmed',
    statusUnavailable: 'Unavailable',
    localNote: 'Local note',
    localNotePlaceholder: 'Short note — saved on this device',
    remove: 'Remove',
    copyPlan: 'Copy plain text',
    print: 'Print',
    clearPlan: 'Clear this plan',
    planStorageWarning: 'Browser storage is not encrypted. Someone with access to this browser profile may be able to read the plan.',
    copied: 'Plan copied as plain text.',
    copyFailed: 'Copy failed. Use Print or copy each item manually.',
    savedTitle: 'Saved resources',
    savedEmpty: 'No saved resources yet.',
    privacyEyebrow: 'Privacy and data',
    privacyTitle: 'Your information stays under your control.',
    privacyIntro: 'BridgeAid uses a general location to find nearby programs. Exact GPS coordinates and eligibility answers are not saved.',
    privacyLocationTitle: 'Location',
    privacyLocationText: 'A general location is saved on this device so searches are easier. GPS coordinates are used only for the current search.',
    clearLocation: 'Clear saved location',
    privacyQuizTitle: 'Eligibility quiz',
    privacyQuizText: 'Quiz answers stay in this tab and are not permanently saved. Do not enter highly sensitive information.',
    clearEligibility: 'Clear eligibility answers',
    privacySavedTitle: 'Saved information',
    privacySavedText: 'Saved resources, cached searches, helper plans, and notes stay in this browser and can be deleted.',
    clearLocalData: 'Clear local BridgeAid data',
    privacyReportsTitle: 'Correction reports',
    privacyReportsText: 'Reports are added to a local correction queue for verification. A report does not immediately replace verified information.',
    privacyConfirm: 'BridgeAid does not guarantee eligibility, capacity, appointments, supplies, or service availability.',
    eligibilityEyebrow: 'Preliminary screening',
    eligibilityTitle: 'Eligibility',
    eligibilityIntro: 'Choose a resource and answer only the questions used by that local program.',
    chooseProgram: 'Choose a program',
    selectProgram: 'Select a resource',
    eligibilityLocation: 'Application location',
    eligibilityLocationHelp: 'Enter the ZIP code, city, county, or state where the person is applying.',
    startEligibility: 'Start eligibility check',
    localProgramUsed: 'Program used',
    locationUsed: 'Location used',
    likelyEligible: 'Likely eligible',
    possiblyEligible: 'Possibly eligible',
    likelyNotEligible: 'Likely not eligible',
    unableDetermine: 'Unable to determine',
    satisfied: 'Requirements that appear satisfied',
    notSatisfied: 'Requirements that may not be satisfied',
    requirementMet: '{requirement}: appears to meet the published rule.',
    requirementNotMet: '{requirement}: may not meet the published rule.',
    missingInfo: 'Missing information',
    missingProgram: 'A local program must be selected.',
    missingLocation: 'The application location is needed.',
    missingLocalRules: 'Verified local eligibility rules are missing.',
    exceptions: 'Relevant exceptions',
    whoQualifies: 'Who qualifies',
    geographicRestrictions: 'Geographic restrictions',
    incomeRequirements: 'Income requirements',
    ageHouseholdRequirements: 'Age or household requirements',
    importantExceptions: 'Important exceptions',
    applicationDeadline: 'Application deadline',
    documents: 'Required documents',
    nextSteps: 'Recommended next steps',
    preliminaryOnly: 'This is a preliminary screening. The organization makes the final decision.',
    answerQuestion: 'Question {current} of {total}',
    continue: 'Continue',
    seeResult: 'See result',
    restartQuiz: 'Clear answers and restart',
    noLocalRules: 'Unable to determine: verified rules for this local program and location are not available.',
    nearbyRulesDiffer: 'Nearby programs may use different rules. This result applies only to the program and location shown.',
    ageRange: 'Age range',
    householdSize: 'Household size',
    incomeRange: 'Approximate household income range',
    housingStatus: 'Housing status',
    employmentStatus: 'Employment status',
    studentStatus: 'Student status',
    insuranceStatus: 'Insurance status',
    disabilityStatus: 'Disability status',
    dependents: 'Number of dependents',
    programConsiderations: 'Program-specific information',
    chooseAnswer: 'Choose an answer',
    under18: 'Under 18',
    age18to24: '18–24',
    age25to59: '25–59',
    age60plus: '60 or older',
    incomeUnknown: 'Not sure',
    incomeUnder20: 'Under $20,000 per year',
    income20to40: '$20,000–$39,999 per year',
    income40to75: '$40,000–$74,999 per year',
    income75plus: '$75,000 or more per year',
    housed: 'Stable housing',
    temporaryHousing: 'Temporary housing',
    unhoused: 'No stable housing',
    employed: 'Employed',
    unemployed: 'Unemployed',
    notWorking: 'Not currently working',
    student: 'Student',
    notStudent: 'Not a student',
    insured: 'Insured',
    uninsured: 'Uninsured',
    disabilityYes: 'Has a disability',
    disabilityNo: 'No disability reported',
    requirementsTitle: 'Local requirements',
    fullRequirements: 'Review the full official requirements',
    registrationTitle: 'Registration help',
    registrationProgress: 'Application guidance · step {current} of {total}',
    registrationStepDocuments: 'Prepare',
    registrationStepApply: 'Apply',
    registrationStepConfirm: 'Confirm',
    registrationNoForm: 'No verified online application was found.',
    registrationUseContact: 'Use the verified contact information below to ask how to apply.',
    registrationNotRequired: 'Registration is not required for this service.',
    registrationPhoneOnly: 'Registration is available by phone or in person.',
    registrationReview: 'Review the application before entering personal information.',
    registrationNeverSubmit: 'BridgeAid never submits an external application or accepts terms for you.',
    previous: 'Previous',
    next: 'Next',
    openApplication: 'Open official application',
    openOfficialSite: 'Open official website',
    applicationProcess: 'Follow these verified application steps:',
    waysToApply: 'Ways to apply',
    applyThroughLocalProvider: 'Through a local provider',
    applyOnline: 'Online',
    applyByPhone: 'By phone',
    applyByMail: 'By mail',
    applyByEmail: 'By email',
    applyByFax: 'By fax',
    applyInPerson: 'In person',
    nationwideEyebrow: 'Help available across the United States',
    nationwideTitle: 'Nationwide Help',
    nationwideIntro: 'Use these verified national tools, hotlines, and official directories without mixing them into nearby local results.',
    nationwideFilters: 'Filter nationwide online resources',
    nationwideAccess: 'Nationwide access',
    nationwideAvailability: 'Nationwide availability',
    whoItHelps: 'Who it helps',
    onlineEligibilityFilter: 'Eligibility',
    applicationMethodFilter: 'Application method',
    filterAll: 'All',
    onlineEligibilityOpen: 'Open to anyone for information or referral',
    onlineEligibilityVaries: 'Eligibility varies by program',
    onlineEligibilityLocalProvider: 'Local provider rules apply',
    localProviderExplanation: 'This national resource connects you to a local provider. The local branch sets its own hours, documents, availability, and final eligibility rules.',
    openOfficialResource: 'Open official resource',
    noOnlineResults: 'No nationwide resources match these filters.',
    startApplication: 'Start application',
    completeQuestionnaire: 'Complete questionnaire',
    scheduleAppointment: 'Schedule appointment',
    downloadApplication: 'Download application',
    viewRequiredDocuments: 'View required documents',
    contactIntake: 'Contact intake',
    callToApply: 'Call to apply',
    appointmentRequirements: 'Appointment requirements',
    callingScript: 'Calling script',
    callingScriptText: 'Hello, I’m calling about {program}. Could you confirm who qualifies, which documents are needed, and how to apply?',
    helperLocationQuestion: 'Where is the person who needs assistance?',
    helperSupportQuestion: 'What types of support are you trying to find?',
    helperAuthorizedDescription: 'Describe the situation using only information you are authorized to share.',
    helperSupportTypes: 'Select one or more support types',
    helperSituationLabel: 'Authorized situation summary',
    helperSituationPlaceholder: 'Include practical constraints, schedules, and priorities—not sensitive identifiers.',
    sharePlan: 'Share plan',
    questionsToAsk: 'Questions to ask',
    questionsToAskPlaceholder: 'Example: Is there space Tuesday? Can documents be submitted online?',
    confirmedAtRequestedTime: 'Confirmed for {time}',
    unavailableAtRequestedTime: 'Not available at {time}',
    uncertainAtRequestedTime: 'Availability is uncertain for {time}',
    whyPrioritized: 'Why this ranking',
    eligibilityResearchPending: 'Eligibility research pending',
    eligibilityNeedsReview: 'Eligibility details require review',
    eligibilityOutOfArea: 'Program does not serve this location',
    eligibilityResearchPendingExplanation: 'Official program sources are queued for review. This is not a technical failure and no rules have been invented.',
    eligibilityReviewExplanation: 'Official sources were found, but the rules were ambiguous and require staff review before screening.',
    eligibilityOutOfAreaExplanation: 'The program’s verified service area does not include the entered location.',
    exportEligibilityCsv: 'Export eligibility records (CSV)',
    eligibilitySourceLink: 'Review official eligibility source',
    onlineEligibilityStructured: 'Published structured eligibility',
    cost: 'Cost',
    reportTitle: 'Report incorrect information',
    reportIntro: 'Choose what appears incorrect. The report will be queued for verification and will not immediately change the resource.',
    reportType: 'What is incorrect?',
    reportAddress: 'Incorrect address',
    reportHours: 'Incorrect hours',
    reportClosed: 'Program closed',
    reportService: 'Service no longer offered',
    reportEligibility: 'Incorrect eligibility information',
    reportRegistration: 'Broken registration link',
    reportDuplicate: 'Duplicate resource',
    reportOther: 'Other',
    reportDetails: 'Optional details',
    reportDetailsPlaceholder: 'Share what you observed without including personal information.',
    submitReport: 'Submit report',
    reportSubmitted: 'Report added to the BridgeAid verification queue.',
    reportQueued: 'Pending source verification',
    reportVerificationProcess: 'BridgeAid will compare the report with official and recent sources. Unclear cases require staff review.',
    assistantName: 'BridgeAI',
    assistantSubtitle: 'Grounded in saved and current sources',
    assistantLoading: 'Checking saved information…',
    assistantSelfOpening: 'What do you need help with right now?',
    assistantHelperOpening: 'Tell me what the person needs and any limits we should consider.',
    chatPlaceholder: 'Ask about resources, hours, eligibility, or applying',
    send: 'Send',
    assistantNeedLocation: 'What city or ZIP code should I search?',
    assistantNeedNeed: 'What kind of help do you need?',
    assistantNoVerified: 'I could not verify a matching local resource. Try another category or call 211 for community-resource referrals.',
    assistantFound: 'I found {count} sourced options near {location}.',
    assistantResourceLine: '{name}. {address} Hours: {hours} Eligibility: {eligibility} Official source: {url}',
    assistantHoursUnknown: 'Hours could not be verified. Check the official source or contact the program before visiting.',
    assistantHoursKnown: 'I found a published schedule for {program}. The current status and full week are shown below.',
    assistantEligibilityUnknown: 'Local eligibility rules could not be verified for {location}.',
    assistantEligibilityKnown: 'I found locally verified eligibility information for {program}. Review the requirements below and confirm with the provider.',
    assistantEligibilityNotPublished: '{program} does not publicly list specific eligibility requirements. Contact the provider for confirmation.',
    assistantLocationKnown: '{program} is located at {address}.',
    assistantApplyUnknown: 'I could not verify an online application. Use the verified phone number or official website shown for the resource.',
    footerNotice: 'Confirm schedules, local eligibility, and application steps with the organization.',
    clearDataDone: 'Local BridgeAid data was cleared.',
    otherNeedRequired: 'Describe the other type of help you need.',
    officialSource: 'Official source',
    typicalLabel: 'Typical hours — confirm before visiting',
    unknown: 'Unknown',
    nonePublished: 'Not published',
    today: 'Today',
    chatLanguageChanged: 'I’ll continue in English.'
  },
  zh: {
    brandTagline: '可靠资源，清晰指引。',
    appTitle: 'BridgeAid — 可靠的社区资源',
    mainNavigation: '主导航',
    openMenu: '打开菜单',
    navHome: '首页',
    navFind: '本地帮助',
    navNationwide: '全美帮助',
    navEligibility: '资格',
    navSaved: '已收藏',
    navPrivacy: '隐私',
    language: '语言',
    modeSelf: '我需要帮助',
    modeHelper: '我在帮助他人',
    switchMode: '切换 BridgeAid 使用方式',
    modeQuestion: '您如何使用 BridgeAid？',
    modeSelfDescription: '为自己查找食物、住宿、医疗等支持。',
    modeHelperDescription: '为他人查找并整理可用资源。',
    cancel: '取消',
    selfEyebrow: '查找附近资源',
    selfHero: '您现在最需要什么？',
    selfSub: '查找附近的免费帮助。',
    helperEyebrow: '助人工作区',
    helperHero: '帮助他人找到支持。',
    helperSub: '回答几个问题，建立一份资源计划。',
    needLabel: '您需要哪类帮助？',
    needChoose: '请选择帮助类型',
    needOther: '其他',
    needOtherLabel: '请说明您需要的帮助',
    needOtherPlaceholder: '例如：上网服务或衣物',
    chooseNeed: '选择当前最急需的帮助',
    situationLabel: '请说明具体情况',
    situationPlaceholder: '例如：我今晚需要食物，而且没有身份证明。',
    required: '必填',
    locationSuggestionsLoading: '正在查找美国地点…',
    notYetVerified: '尚未核实；发现于 {date}',
    discoveryRunning: '此地点可以搜索。现已显示已核实结果，并继续发现更多资源。',
    loadMore: '加载更多（剩余 {remaining}）',
    savedNeedsVerification: '有 {count} 个已保存项目因当前信息未核实而隐藏。',
    retryVerification: '重试核实',
    multipleMethods: '可使用多种方式',
    categoryAll: '全部服务',
    categoryFood: '食物援助',
    categoryShelter: '住宿与住房',
    categorySafe: '安全场所',
    categoryHealth: '医疗服务',
    categoryMental: '心理健康服务',
    categoryHygiene: '淋浴、洗衣与卫生用品',
    categoryTransport: '交通帮助',
    categoryBenefits: '福利与经济援助',
    categoryJobs: '就业与培训',
    categoryEducation: '教育与奖学金',
    categoryLegal: '法律帮助',
    categoryFamily: '家庭与托儿支持',
    categoryDisability: '残障服务',
    categoryVeteran: '退伍军人服务',
    categoryImmigration: '移民援助',
    categoryInternet: '互联网与技术',
    locationLabel: '城市、邮编、县、社区、地址或地标',
    locationPlaceholder: '例如：98101 或 Seattle, WA',
    locationPrivacy: '大概位置即可。GPS 精确坐标不会保存。',
    distanceUnit: '距离单位',
    miles: '英里',
    kilometers: '公里',
    radius: '搜索范围',
    radiusMiles: '{value} 英里',
    radiusKilometers: '{value} 公里',
    travelMode: '出行方式',
    walking: '步行',
    transit: '公共交通',
    driving: '驾车',
    useLocation: '使用我的位置',
    findResources: '查找资源',
    communitySupport: '社区资源',
    call211: '拨打 211',
    call211Tooltip: '拨打 211，免费、保密地获取当地资源转介。',
    safetySupportNote: 'BridgeAid 是资源查询工具。如果有人正面临紧急危险，请联系当地紧急服务。',
    noHomeResources: '请选择需求并输入位置，之后才会显示已核实的资源。',
    searchResults: '资源搜索结果',
    resultsFor: '{location} 附近的“{need}”资源',
    resultsCount: '共 {count} 项资源',
    everyResultSourced: '每项结果都附有可追溯来源。',
    loading: '正在查看已保存资源和最新公开信息…',
    offline: '当前处于离线状态。仅显示仍在核实有效期内的资源。',
    cached: '正在显示近期核实的结果。',
    refreshed: '当前结果已核实。',
    stale: '过期的保存结果已隐藏，并已排队等待重新核实。',
    searchError: '目前无法核实资源信息。',
    searchUnavailable: '目前无法核实资源信息。不会显示过期的保存结果。',
    searchPartialResults: '正在显示已核实的保存资源。实时搜索暂时无法刷新，请再次确认时间敏感信息。',
    retrySearch: '重试',
    locationRequired: '请选择需求并输入位置后再搜索。',
    locationAmbiguous: '匹配到多个地点，请补充州名或邮编。',
    locationNotFound: '未找到该地点。请检查拼写，或补充州名或邮编。',
    locationSuggestions: '您指的是以下地点之一吗？',
    locationDenied: '未获得定位权限，请手动输入城市或邮编。',
    locationTimeout: '定位请求超时，请手动输入城市或邮编。',
    storageBlocked: '浏览器阻止了本地保存。本次使用不受影响，但更改可能无法保留。',
    filters: '筛选结果',
    filterOpenNow: '现在营业',
    filterAvailableToday: '今天可用',
    filterWalkIn: '可直接到访',
    filterNoId: '无需身份证明',
    filterNoRegistration: '无需登记',
    filterAccessible: '轮椅可通行',
    filterVerifiedEligibility: '资格要求已在当地核实',
    filterLanguage: '可提供的语言',
    filterLanguagePlaceholder: '例如：中文',
    clearFilters: '清除筛选',
    noResults: '没有符合当前筛选条件的已核实资源。请清除筛选或扩大搜索范围。',
    sortBy: '排序方式',
    sortNearest: '距离最近',
    sortFarthest: '距离最远',
    sortRelevant: '最相关',
    sortOpenSoonest: '最早开放',
    category: '服务类别',
    address: '完整地址',
    addressUnavailable: '请打开官方目录，选择当地项目后查看具体地址。',
    distance: '步行距离',
    walkingEstimate: '{distance} · 步行约 {minutes} 分钟',
    hours: '开放时间',
    typicalHours: '通常开放时间',
    schedule: '服务时间',
    schedulePublished: '已公布时间',
    scheduleUncertain: '暂时无法核实服务时间',
    scheduleResearching: '正在查询官方时间信息',
    hoursNotPubliclyListed: '未公开列出开放时间',
    appointmentOnly: '仅限预约',
    onlineAvailable: '可在线使用',
    open24Hours: '24 小时开放',
    temporaryClosure: '暂时关闭',
    opensAt: '{time} 开放',
    holidayHours: '节假日时间',
    specialHours: '特殊时间',
    hoursSource: '时间来源',
    dayMonday: '星期一',
    dayTuesday: '星期二',
    dayWednesday: '星期三',
    dayThursday: '星期四',
    dayFriday: '星期五',
    daySaturday: '星期六',
    daySunday: '星期日',
    availability: '当前服务状态',
    availabilityConfirm: '前往前请先确认',
    openNow: '现在营业',
    closed: '已关闭',
    openingSoon: '即将开放',
    availableToday: '今天可用',
    upcomingEvent: '近期活动',
    verifiedPreviously: '此前已核实；时间敏感信息请再次确认。',
    communitySourced: '来自社区公开数据；请向机构确认。',
    needsVerification: '需要进一步确认。',
    eligibilitySummary: '资格',
    eligibilityLocalUnknown: '暂时无法核实当地资格规则。',
    eligibilityNotPubliclyListed: '该项目未公开列出具体资格要求。请联系服务机构确认。',
    noEligibilityRequirementsListed: '未列出资格限制',
    noEligibilityRequirementsExplanation: '该服务机构未公开列出具体资格限制。请联系机构确认服务是否可用。',
    eligibilityTemporarilyUnavailable: '资格信息暂时不可用',
    eligibilityTemporarilyUnavailableExplanation: '目前无法核实资格信息。请稍后重试，或在依赖此信息前联系服务机构。',
    registrationRequirement: '申请方式',
    officialWebsite: '官方网站',
    officialApplication: '官方申请入口',
    lastVerified: '最后核实日期',
    verification: '核实状态',
    sources: '信息来源',
    sourceNumber: '来源 {number}',
    conflictingInfo: '信息存在冲突',
    aiSummary: 'BridgeAid 摘要',
    confirmOrganization: '请向服务机构确认资格和服务是否可用。',
    call: '致电',
    walkingDirections: '步行路线',
    transitDirections: '公交路线',
    drivingDirections: '驾车路线',
    viewRequirements: '查看要求',
    checkEligibility: '资格',
    registrationHelp: '获取申请帮助',
    reportIncorrect: '报告错误信息',
    save: '收藏',
    savedAction: '已收藏',
    selectPlan: '加入计划',
    inPlan: '已加入计划',
    compare: '比较',
    comparison: '资源对比',
    clearComparison: '清除对比',
    compareResource: '资源',
    compareEligibility: '当地资格',
    compareSource: '官方来源',
    close: '关闭',
    helperIntakeStep: '引导式信息收集 · 已标出必填项',
    helperIntakeTitle: '资源计划需要考虑哪些情况？',
    clearIntake: '清除信息',
    privacyNotice: '请只填写您获准使用的信息。备注仅保存在本设备。',
    sensitiveWarning: '请勿填写姓名、证件号码、银行信息、密码或证件照片。',
    optional: '选填',
    immediateNeed: '当前最急需的帮助',
    safetyTonight: '今晚是否安全',
    safe: '安全',
    notSafe: '不安全',
    unsure: '不确定',
    ageGroup: '年龄段',
    children: '是否有儿童',
    yes: '是',
    no: '否',
    veteranStatus: '退伍军人情况',
    preferNot: '不愿回答',
    identification: '是否有身份证明',
    someDocuments: '有部分材料',
    transportation: '可用交通方式',
    walkingOnly: '只能步行',
    car: '有车',
    needsRide: '需要接送',
    phoneAccess: '电话使用情况',
    reliable: '可稳定使用',
    limited: '只能有限使用',
    noPhone: '没有电话',
    accessibilityNeeds: '无障碍需求',
    preferredLanguage: '首选语言',
    familyRestrictions: '家庭入住限制',
    petRestrictions: '宠物限制',
    genderRestrictions: '性别限制',
    ageRestrictions: '年龄限制',
    sobrietyRestrictions: '戒酒戒毒相关限制',
    additionalNotes: '其他备注',
    localDeviceNote: '保存在本设备',
    buildOptions: '生成资源选项',
    planLocal: '本地计划 · 已选 {count} 项',
    resourcePlan: '资源计划',
    need: '需求',
    location: '位置',
    notEntered: '尚未填写',
    created: '创建时间',
    updated: '更新时间',
    planEmpty: '请选择资源加入计划。备注和状态仅保存在本设备。',
    status: '联系状态',
    statusNotContacted: '尚未联系',
    statusCalled: '已致电',
    statusConfirmed: '已确认',
    statusUnavailable: '不可用',
    localNote: '本地备注',
    localNotePlaceholder: '简短备注，仅保存在本设备',
    remove: '移除',
    copyPlan: '复制纯文本',
    print: '打印',
    clearPlan: '清除整份计划',
    planStorageWarning: '浏览器存储未加密。能使用此浏览器账户的人可能看到这份计划。',
    copied: '已复制资源计划。',
    copyFailed: '复制失败，请使用打印功能或逐项复制。',
    savedTitle: '已收藏资源',
    savedEmpty: '还没有收藏任何资源。',
    privacyEyebrow: '隐私与数据',
    privacyTitle: '您的信息由您掌控。',
    privacyIntro: 'BridgeAid 使用大概位置查找附近项目。GPS 精确坐标和资格问卷答案不会保存。',
    privacyLocationTitle: '位置信息',
    privacyLocationText: '大概位置会保存在本设备，方便下次搜索。GPS 坐标仅用于当前搜索。',
    clearLocation: '清除已保存位置',
    privacyQuizTitle: '资格问卷',
    privacyQuizText: '问卷答案只在当前标签页中使用，不会长期保存。请勿填写高度敏感信息。',
    clearEligibility: '清除资格问卷答案',
    privacySavedTitle: '已保存信息',
    privacySavedText: '收藏资源、缓存搜索、助人计划和备注保存在本浏览器中，可随时删除。',
    clearLocalData: '清除本地 BridgeAid 数据',
    privacyReportsTitle: '纠错报告',
    privacyReportsText: '纠错报告会加入本地核实队列，不会立即替换已经核实的信息。',
    privacyConfirm: 'BridgeAid 不保证资格、名额、预约、物资或服务一定可用。',
    eligibilityEyebrow: '初步资格筛查',
    eligibilityTitle: '资格',
    eligibilityIntro: '请选择资源，并只回答该当地项目实际使用的问题。',
    chooseProgram: '选择项目',
    selectProgram: '请选择一项资源',
    eligibilityLocation: '申请所在地',
    eligibilityLocationHelp: '请输入申请人所在的邮编、城市、县或州。',
    startEligibility: '开始资格初筛',
    localProgramUsed: '所用项目',
    locationUsed: '所用地区',
    likelyEligible: '可能符合资格',
    possiblyEligible: '有可能符合资格',
    likelyNotEligible: '可能不符合资格',
    unableDetermine: '无法判断',
    satisfied: '看起来符合的要求',
    notSatisfied: '可能不符合的要求',
    requirementMet: '{requirement}：看起来符合已公布规则。',
    requirementNotMet: '{requirement}：可能不符合已公布规则。',
    missingInfo: '缺少的信息',
    missingProgram: '需要选择一个当地项目。',
    missingLocation: '需要填写申请所在地。',
    missingLocalRules: '缺少已核实的当地资格规则。',
    exceptions: '相关例外情况',
    whoQualifies: '适用人群',
    geographicRestrictions: '地区限制',
    incomeRequirements: '收入要求',
    ageHouseholdRequirements: '年龄或家庭要求',
    importantExceptions: '重要例外',
    applicationDeadline: '申请截止时间',
    documents: '所需材料',
    nextSteps: '建议下一步',
    preliminaryOnly: '此结果仅供初步筛查，最终资格由服务机构决定。',
    answerQuestion: '第 {current} 题，共 {total} 题',
    continue: '继续',
    seeResult: '查看结果',
    restartQuiz: '清除答案并重新开始',
    noLocalRules: '无法判断：目前没有可核实的当地项目资格规则。',
    nearbyRulesDiffer: '附近不同项目的规则可能不同。本结果只适用于上方显示的项目和地区。',
    ageRange: '年龄段',
    householdSize: '家庭人数',
    incomeRange: '家庭大致收入范围',
    housingStatus: '住房情况',
    employmentStatus: '就业情况',
    studentStatus: '学生身份',
    insuranceStatus: '保险情况',
    disabilityStatus: '残障情况',
    dependents: '受抚养人数',
    programConsiderations: '项目特定情况',
    chooseAnswer: '请选择',
    under18: '18 岁以下',
    age18to24: '18 至 24 岁',
    age25to59: '25 至 59 岁',
    age60plus: '60 岁及以上',
    incomeUnknown: '不确定',
    incomeUnder20: '每年低于 20,000 美元',
    income20to40: '每年 20,000 至 39,999 美元',
    income40to75: '每年 40,000 至 74,999 美元',
    income75plus: '每年 75,000 美元或以上',
    housed: '住房稳定',
    temporaryHousing: '临时住房',
    unhoused: '没有稳定住房',
    employed: '在职',
    unemployed: '失业',
    notWorking: '目前未工作',
    student: '在校学生',
    notStudent: '不是学生',
    insured: '有保险',
    uninsured: '没有保险',
    disabilityYes: '有残障',
    disabilityNo: '没有报告残障',
    requirementsTitle: '当地项目要求',
    fullRequirements: '查看完整官方要求',
    registrationTitle: '申请帮助',
    registrationProgress: '申请指引 · 第 {current} 步，共 {total} 步',
    registrationStepDocuments: '准备材料',
    registrationStepApply: '开始申请',
    registrationStepConfirm: '确认信息',
    registrationNoForm: '没有找到已核实的在线申请入口。',
    registrationUseContact: '请使用下方已核实的联系方式询问申请方式。',
    registrationNotRequired: '此服务无需登记。',
    registrationPhoneOnly: '此项目需要通过电话或现场申请。',
    registrationReview: '填写个人信息前，请先核对申请页面。',
    registrationNeverSubmit: 'BridgeAid 不会代您提交外部申请，也不会代您同意法律条款。',
    previous: '上一步',
    next: '下一步',
    openApplication: '打开官方申请',
    openOfficialSite: '打开官方网站',
    applicationProcess: '请按照以下已核实步骤申请：',
    waysToApply: '申请方式',
    applyThroughLocalProvider: '通过当地服务机构',
    applyOnline: '在线申请',
    applyByPhone: '电话申请',
    applyByMail: '邮寄申请',
    applyByEmail: '电子邮件申请',
    applyByFax: '传真申请',
    applyInPerson: '现场申请',
    nationwideEyebrow: '全美可用的帮助',
    nationwideTitle: '全美援助',
    nationwideIntro: '使用经过核实的全国工具、热线和官方目录；这些资源不会混入附近的本地搜索结果。',
    nationwideFilters: '筛选全美在线资源',
    nationwideAccess: '全美可用',
    nationwideAvailability: '全美可用范围',
    whoItHelps: '服务对象',
    onlineEligibilityFilter: '资格',
    applicationMethodFilter: '申请方式',
    filterAll: '全部',
    onlineEligibilityOpen: '任何人均可获取信息或转介',
    onlineEligibilityVaries: '资格因项目而异',
    onlineEligibilityLocalProvider: '适用当地服务机构规则',
    localProviderExplanation: '此全国资源会将您连接到当地服务机构。当地机构决定营业时间、所需文件、服务名额和最终资格规则。',
    openOfficialResource: '打开官方资源',
    noOnlineResults: '没有符合这些筛选条件的全美资源。',
    startApplication: '开始申请',
    completeQuestionnaire: '填写资格问卷',
    scheduleAppointment: '预约',
    downloadApplication: '下载申请表',
    viewRequiredDocuments: '查看所需材料',
    contactIntake: '联系受理人员',
    callToApply: '致电申请',
    appointmentRequirements: '预约要求',
    callingScript: '电话询问话术',
    callingScriptText: '您好，我想咨询 {program}。请问申请资格、所需材料和申请方式分别是什么？',
    helperLocationQuestion: '需要帮助的人在哪里？',
    helperSupportQuestion: '您正在寻找哪些类型的支持？',
    helperAuthorizedDescription: '仅使用您获授权分享的信息描述情况。',
    helperSupportTypes: '选择一个或多个支持类型',
    helperSituationLabel: '经授权的情况摘要',
    helperSituationPlaceholder: '可填写实际限制、时间安排和优先事项；请勿填写敏感身份信息。',
    sharePlan: '分享计划',
    questionsToAsk: '要询问的问题',
    questionsToAskPlaceholder: '例如：周二还有名额吗？可以在线提交材料吗？',
    confirmedAtRequestedTime: '已确认在 {time} 可用',
    unavailableAtRequestedTime: '{time} 不可用',
    uncertainAtRequestedTime: '无法确认 {time} 是否可用',
    whyPrioritized: '排序依据',
    eligibilityResearchPending: '资格信息正在研究',
    eligibilityNeedsReview: '资格详情需要审核',
    eligibilityOutOfArea: '该项目不服务此地点',
    eligibilityResearchPendingExplanation: '官方项目来源已进入审核队列。这不是技术故障，系统也没有编造规则。',
    eligibilityReviewExplanation: '已找到官方来源，但规则存在歧义，需要工作人员审核后才能筛查。',
    eligibilityOutOfAreaExplanation: '该项目已核实的服务区域不包括所输入地点。',
    exportEligibilityCsv: '导出资格记录（CSV）',
    eligibilitySourceLink: '查看官方资格信息来源',
    onlineEligibilityStructured: '已发布结构化资格要求',
    cost: '费用',
    reportTitle: '报告错误信息',
    reportIntro: '请选择有误的内容。报告会进入核实队列，不会立即更改资源记录。',
    reportType: '哪项信息有误？',
    reportAddress: '地址错误',
    reportHours: '开放时间错误',
    reportClosed: '项目已关闭',
    reportService: '已不再提供该服务',
    reportEligibility: '资格信息错误',
    reportRegistration: '申请链接失效',
    reportDuplicate: '重复资源',
    reportOther: '其他',
    reportDetails: '补充说明（选填）',
    reportDetailsPlaceholder: '请描述您看到的情况，不要填写个人信息。',
    submitReport: '提交报告',
    reportSubmitted: '报告已加入 BridgeAid 核实队列。',
    reportQueued: '等待来源核实',
    reportVerificationProcess: 'BridgeAid 将对照官方和近期公开来源。无法确认或信息冲突的情况需要工作人员审核。',
    assistantName: 'BridgeAI',
    assistantSubtitle: '依据已保存资源和最新公开来源',
    assistantLoading: '正在查看已保存的信息…',
    assistantSelfOpening: '您现在需要哪方面的帮助？',
    assistantHelperOpening: '请告诉我对方需要什么，以及需要考虑哪些限制。',
    chatPlaceholder: '询问资源、开放时间、资格或申请方式',
    send: '发送',
    assistantNeedLocation: '请告诉我需要搜索的城市或邮编。',
    assistantNeedNeed: '请问您需要哪一类帮助？',
    assistantNoVerified: '暂时没有核实到符合条件的当地资源。您可以尝试其他类别，或拨打 211 查询社区资源。',
    assistantFound: '我在 {location} 附近找到了 {count} 个有来源的选项。',
    assistantResourceLine: '{name}。地址：{address}。时间：{hours}。资格：{eligibility}。官方来源：{url}',
    assistantHoursUnknown: '暂时无法核实开放时间，请查看官方来源或在前往前联系该项目。',
    assistantHoursKnown: '我找到了 {program} 已公布的开放时间。下方显示当前状态和一周时间。',
    assistantEligibilityUnknown: '暂时无法核实 {location} 的当地资格规则。',
    assistantEligibilityKnown: '我找到了 {program} 已在当地核实的资格信息。请查看下方要求，并向服务机构确认。',
    assistantEligibilityNotPublished: '{program} 未公开列出具体资格要求。请联系服务机构确认。',
    assistantLocationKnown: '{program} 位于 {address}。',
    assistantApplyUnknown: '暂时无法核实在线申请入口，请使用资源卡中已核实的电话或官方网站。',
    footerNotice: '请向服务机构确认开放时间、当地资格和申请步骤。',
    clearDataDone: '已清除本地 BridgeAid 数据。',
    otherNeedRequired: '请说明您需要的其他帮助。',
    officialSource: '官方来源',
    typicalLabel: '通常开放时间，前往前请确认',
    unknown: '未知',
    nonePublished: '未公布',
    today: '今天',
    chatLanguageChanged: '我会继续使用中文。'
  },
  es: {
    brandTagline: 'Recursos confiables. Pasos claros.',
    appTitle: 'BridgeAid — recursos comunitarios confiables',
    mainNavigation: 'Navegación principal',
    openMenu: 'Abrir menú',
    navHome: 'Inicio',
    navFind: 'Ayuda local',
    navNationwide: 'Ayuda nacional',
    navEligibility: 'Elegibilidad',
    navSaved: 'Guardados',
    navPrivacy: 'Privacidad',
    language: 'Idioma',
    modeSelf: 'Necesito ayuda',
    modeHelper: 'Estoy ayudando a alguien',
    switchMode: 'Cambiar cómo usa BridgeAid',
    modeQuestion: '¿Cómo está usando BridgeAid?',
    modeSelfDescription: 'Busque alimentos, alojamiento, atención médica y otros apoyos para usted.',
    modeHelperDescription: 'Busque y organice recursos para otra persona.',
    cancel: 'Cancelar',
    selfEyebrow: 'Ayuda cercana',
    selfHero: '¿Qué necesita en este momento?',
    selfSub: 'Encuentre ayuda gratuita cerca de usted.',
    helperEyebrow: 'Espacio para ayudar',
    helperHero: 'Ayude a alguien a encontrar apoyo.',
    helperSub: 'Responda unas preguntas para preparar un plan de recursos.',
    needLabel: '¿Qué tipo de ayuda necesita?',
    needChoose: 'Elija un tipo de ayuda',
    needOther: 'Otra',
    needOtherLabel: 'Describa la ayuda que necesita',
    needOtherPlaceholder: 'Por ejemplo: acceso a internet o ropa',
    chooseNeed: 'Elija una necesidad inmediata',
    situationLabel: 'Describa la situación exacta',
    situationPlaceholder: 'Ejemplo: Necesito comida esta noche y no tengo identificación.',
    required: 'Obligatorio',
    locationSuggestionsLoading: 'Buscando ubicaciones en EE. UU.…',
    notYetVerified: 'Aún no verificado; descubierto el {date}',
    discoveryRunning: 'Esta ubicación se puede buscar. Se muestran resultados verificados mientras continúa el descubrimiento.',
    loadMore: 'Cargar más (quedan {remaining})',
    savedNeedsVerification: 'Se ocultaron {count} elemento(s) guardado(s) porque no hay información actual verificada.',
    retryVerification: 'Reintentar verificación',
    multipleMethods: 'Hay varios métodos disponibles',
    categoryAll: 'Todos los servicios',
    categoryFood: 'Alimentos',
    categoryShelter: 'Alojamiento y vivienda',
    categorySafe: 'Lugar seguro',
    categoryHealth: 'Atención médica',
    categoryMental: 'Salud mental',
    categoryHygiene: 'Ducha, lavandería e higiene',
    categoryTransport: 'Transporte',
    categoryBenefits: 'Beneficios y ayuda económica',
    categoryJobs: 'Empleo y capacitación',
    categoryEducation: 'Educación y becas',
    categoryLegal: 'Ayuda legal',
    categoryFamily: 'Apoyo familiar y cuidado infantil',
    categoryDisability: 'Servicios para personas con discapacidad',
    categoryVeteran: 'Servicios para veteranos',
    categoryImmigration: 'Asistencia migratoria',
    categoryInternet: 'Internet y tecnología',
    locationLabel: 'Ciudad, código postal, condado, vecindario, dirección o punto de referencia',
    locationPlaceholder: 'Por ejemplo: 98101 o Seattle, WA',
    locationPrivacy: 'Una ubicación general es suficiente. Las coordenadas exactas del GPS no se guardan.',
    distanceUnit: 'Unidad de distancia',
    miles: 'Millas',
    kilometers: 'Kilómetros',
    radius: 'Radio de búsqueda',
    radiusMiles: '{value,plural,milla,millas}',
    radiusKilometers: '{value} km',
    travelMode: 'Cómo llegar',
    walking: 'A pie',
    transit: 'Transporte público',
    driving: 'En auto',
    useLocation: 'Usar mi ubicación',
    findResources: 'Buscar recursos',
    communitySupport: 'Recursos comunitarios',
    call211: 'Llamar al 211',
    call211Tooltip: 'Llame al 211 para recibir referencias locales gratuitas y confidenciales.',
    safetySupportNote: 'BridgeAid es un directorio de recursos. Si alguien está en peligro inmediato, comuníquese con los servicios de emergencia locales.',
    noHomeResources: 'Elija una necesidad y una ubicación para ver recursos verificados.',
    searchResults: 'Resultados de recursos',
    resultsFor: 'Resultados para {need} cerca de {location}',
    resultsCount: '{count} recursos',
    everyResultSourced: 'Cada resultado incluye una fuente rastreable.',
    loading: 'Consultando recursos guardados y fuentes actuales…',
    offline: 'No tiene conexión. Solo se muestran recursos que siguen dentro de su período de verificación.',
    cached: 'Mostrando resultados verificados recientemente.',
    refreshed: 'Se verificaron los resultados actuales.',
    stale: 'Los resultados guardados vencidos se ocultaron y se enviaron para nueva verificación.',
    searchError: 'No se pudo verificar la información actual de los recursos.',
    searchUnavailable: 'No se pudo verificar la información actual. No se muestran resultados guardados vencidos.',
    searchPartialResults: 'Se muestran recursos guardados y verificados. La búsqueda en vivo no pudo actualizarse; confirme los datos que cambian con el tiempo.',
    retrySearch: 'Reintentar',
    locationRequired: 'Elija una necesidad e ingrese una ubicación para buscar.',
    locationAmbiguous: 'Hay más de una ubicación posible. Agregue el estado o el código postal.',
    locationNotFound: 'No se encontró la ubicación. Revise la ortografía o agregue el estado o código postal.',
    locationSuggestions: '¿Quiso decir una de estas ubicaciones?',
    locationDenied: 'No se autorizó la ubicación. Ingrese una ciudad o código postal.',
    locationTimeout: 'La solicitud de ubicación tardó demasiado. Ingrese una ciudad o código postal.',
    storageBlocked: 'El navegador impidió guardar datos localmente. La sesión funciona, pero los cambios podrían no conservarse.',
    filters: 'Filtrar resultados',
    filterOpenNow: 'Abierto ahora',
    filterAvailableToday: 'Disponible hoy',
    filterWalkIn: 'Acepta visitas sin cita',
    filterNoId: 'No requiere identificación',
    filterNoRegistration: 'No requiere inscripción',
    filterAccessible: 'Accesible para silla de ruedas',
    filterVerifiedEligibility: 'Elegibilidad verificada localmente',
    filterLanguage: 'Idioma disponible',
    filterLanguagePlaceholder: 'Por ejemplo: español',
    clearFilters: 'Borrar filtros',
    noResults: 'Ningún recurso verificado coincide con estos filtros. Quite un filtro o amplíe la búsqueda.',
    sortBy: 'Ordenar por',
    sortNearest: 'Más cercano',
    sortFarthest: 'Más lejano',
    sortRelevant: 'Más relevante',
    sortOpenSoonest: 'Abre más pronto',
    category: 'Categoría de servicio',
    address: 'Dirección completa',
    addressUnavailable: 'Abra el directorio oficial para elegir un programa local y ver su dirección.',
    distance: 'Distancia a pie',
    walkingEstimate: '{distance} · unos {minutes} min a pie',
    hours: 'Horario',
    typicalHours: 'Horario habitual',
    schedule: 'Calendario',
    schedulePublished: 'Horario publicado',
    scheduleUncertain: 'No se pudo verificar el horario',
    scheduleResearching: 'Consultando fuentes oficiales de horarios',
    hoursNotPubliclyListed: 'Horario no publicado',
    appointmentOnly: 'Solo con cita',
    onlineAvailable: 'Disponible en línea',
    open24Hours: 'Abierto las 24 horas',
    temporaryClosure: 'Cerrado temporalmente',
    opensAt: 'Abre a las {time}',
    holidayHours: 'Horario de días festivos',
    specialHours: 'Horario especial',
    hoursSource: 'Fuente del horario',
    dayMonday: 'Lunes',
    dayTuesday: 'Martes',
    dayWednesday: 'Miércoles',
    dayThursday: 'Jueves',
    dayFriday: 'Viernes',
    daySaturday: 'Sábado',
    daySunday: 'Domingo',
    availability: 'Disponibilidad actual',
    availabilityConfirm: 'Confirme antes de ir',
    openNow: 'Abierto ahora',
    closed: 'Cerrado',
    openingSoon: 'Abrirá pronto',
    availableToday: 'Disponible hoy',
    upcomingEvent: 'Próximo evento',
    verifiedPreviously: 'Verificado anteriormente; confirme los datos que cambian con el tiempo.',
    communitySourced: 'Datos comunitarios; confirme con la organización.',
    needsVerification: 'Requiere confirmación.',
    eligibilitySummary: 'Elegibilidad',
    eligibilityLocalUnknown: 'No se pudieron verificar las reglas locales de elegibilidad.',
    eligibilityNotPubliclyListed: 'Este programa no publica requisitos específicos de elegibilidad. Comuníquese con el proveedor para confirmarlos.',
    noEligibilityRequirementsListed: 'No hay requisitos de elegibilidad publicados',
    noEligibilityRequirementsExplanation: 'Este proveedor no publica restricciones específicas de elegibilidad. Comuníquese con el proveedor para confirmar la disponibilidad.',
    eligibilityTemporarilyUnavailable: 'Información de elegibilidad no disponible temporalmente',
    eligibilityTemporarilyUnavailableExplanation: 'No se pudo verificar la información actual de elegibilidad. Vuelva a intentarlo más tarde o comuníquese con el proveedor.',
    registrationRequirement: 'Cómo solicitar',
    officialWebsite: 'Sitio oficial',
    officialApplication: 'Solicitud oficial',
    lastVerified: 'Última verificación',
    verification: 'Verificación',
    sources: 'Fuentes',
    sourceNumber: 'Fuente {number}',
    conflictingInfo: 'Información contradictoria',
    aiSummary: 'Resumen de BridgeAid',
    confirmOrganization: 'Confirme la elegibilidad y disponibilidad con la organización.',
    call: 'Llamar',
    walkingDirections: 'Ruta a pie',
    transitDirections: 'Ruta en transporte público',
    drivingDirections: 'Ruta en auto',
    viewRequirements: 'Ver requisitos',
    checkEligibility: 'Elegibilidad',
    registrationHelp: 'Obtener ayuda para solicitar',
    reportIncorrect: 'Reportar información incorrecta',
    save: 'Guardar',
    savedAction: 'Guardado',
    selectPlan: 'Agregar al plan',
    inPlan: 'En el plan',
    compare: 'Comparar',
    comparison: 'Comparar recursos',
    clearComparison: 'Borrar comparación',
    compareResource: 'Recurso',
    compareEligibility: 'Elegibilidad local',
    compareSource: 'Fuente oficial',
    close: 'Cerrar',
    helperIntakeStep: 'Entrevista guiada · campos obligatorios marcados',
    helperIntakeTitle: '¿Qué debe considerar el plan?',
    clearIntake: 'Borrar respuestas',
    privacyNotice: 'Ingrese solo información que tiene permiso de usar. Las notas quedan en este dispositivo.',
    sensitiveWarning: 'No ingrese nombres, números de documentos, datos bancarios, contraseñas ni fotos de documentos.',
    optional: 'Opcional',
    immediateNeed: 'Necesidad inmediata',
    safetyTonight: 'Seguridad esta noche',
    safe: 'A salvo',
    notSafe: 'No está a salvo',
    unsure: 'No se sabe',
    ageGroup: 'Grupo de edad',
    children: 'Hay menores involucrados',
    yes: 'Sí',
    no: 'No',
    veteranStatus: 'Condición de veterano',
    preferNot: 'Prefiere no responder',
    identification: 'Identificación disponible',
    someDocuments: 'Algunos documentos',
    transportation: 'Transporte disponible',
    walkingOnly: 'Solo a pie',
    car: 'Auto',
    needsRide: 'Necesita transporte',
    phoneAccess: 'Acceso a teléfono',
    reliable: 'Confiable',
    limited: 'Limitado',
    noPhone: 'Sin teléfono',
    accessibilityNeeds: 'Necesidades de accesibilidad',
    preferredLanguage: 'Idioma preferido',
    familyRestrictions: 'Restricciones familiares',
    petRestrictions: 'Restricciones sobre mascotas',
    genderRestrictions: 'Restricciones de género',
    ageRestrictions: 'Restricciones de edad',
    sobrietyRestrictions: 'Requisitos de sobriedad',
    additionalNotes: 'Notas adicionales',
    localDeviceNote: 'Guardado en este dispositivo',
    buildOptions: 'Crear opciones de recursos',
    planLocal: 'Plan local · {count} seleccionados',
    resourcePlan: 'Plan de recursos',
    need: 'Necesidad',
    location: 'Ubicación',
    notEntered: 'Sin ingresar',
    created: 'Creado',
    updated: 'Actualizado',
    planEmpty: 'Seleccione recursos para preparar un plan. Las notas y el estado quedan en este dispositivo.',
    status: 'Estado',
    statusNotContacted: 'Sin contactar',
    statusCalled: 'Se llamó',
    statusConfirmed: 'Confirmado',
    statusUnavailable: 'No disponible',
    localNote: 'Nota local',
    localNotePlaceholder: 'Nota breve, guardada en este dispositivo',
    remove: 'Quitar',
    copyPlan: 'Copiar como texto',
    print: 'Imprimir',
    clearPlan: 'Borrar todo el plan',
    planStorageWarning: 'El almacenamiento del navegador no está cifrado. Alguien con acceso a este perfil podría leer el plan.',
    copied: 'El plan se copió como texto.',
    copyFailed: 'No se pudo copiar. Use Imprimir o copie cada elemento.',
    savedTitle: 'Recursos guardados',
    savedEmpty: 'Todavía no hay recursos guardados.',
    privacyEyebrow: 'Privacidad y datos',
    privacyTitle: 'Usted mantiene el control de su información.',
    privacyIntro: 'BridgeAid usa una ubicación general para encontrar programas cercanos. No guarda coordenadas exactas del GPS ni respuestas de elegibilidad.',
    privacyLocationTitle: 'Ubicación',
    privacyLocationText: 'La ubicación general se guarda en este dispositivo para facilitar las búsquedas. El GPS se usa solo en la búsqueda actual.',
    clearLocation: 'Borrar ubicación guardada',
    privacyQuizTitle: 'Cuestionario de elegibilidad',
    privacyQuizText: 'Las respuestas permanecen solo en esta pestaña y no se guardan de forma permanente. No ingrese información muy sensible.',
    clearEligibility: 'Borrar respuestas de elegibilidad',
    privacySavedTitle: 'Información guardada',
    privacySavedText: 'Los recursos, búsquedas, planes y notas guardados permanecen en este navegador y se pueden borrar.',
    clearLocalData: 'Borrar datos locales de BridgeAid',
    privacyReportsTitle: 'Reportes de correcciones',
    privacyReportsText: 'Los reportes se agregan a una cola local de verificación. Un reporte no reemplaza inmediatamente información verificada.',
    privacyConfirm: 'BridgeAid no garantiza elegibilidad, cupos, citas, suministros ni disponibilidad del servicio.',
    eligibilityEyebrow: 'Evaluación preliminar',
    eligibilityTitle: 'Elegibilidad',
    eligibilityIntro: 'Elija un recurso y responda solo las preguntas que utiliza ese programa local.',
    chooseProgram: 'Elegir programa',
    selectProgram: 'Seleccione un recurso',
    eligibilityLocation: 'Ubicación de la solicitud',
    eligibilityLocationHelp: 'Ingrese el código postal, la ciudad, el condado o el estado desde donde se solicita.',
    startEligibility: 'Comenzar la evaluación',
    localProgramUsed: 'Programa utilizado',
    locationUsed: 'Ubicación utilizada',
    likelyEligible: 'Probablemente elegible',
    possiblyEligible: 'Posiblemente elegible',
    likelyNotEligible: 'Probablemente no elegible',
    unableDetermine: 'No se puede determinar',
    satisfied: 'Requisitos que parecen cumplirse',
    notSatisfied: 'Requisitos que podrían no cumplirse',
    requirementMet: '{requirement}: parece cumplir la regla publicada.',
    requirementNotMet: '{requirement}: podría no cumplir la regla publicada.',
    missingInfo: 'Información faltante',
    missingProgram: 'Se debe elegir un programa local.',
    missingLocation: 'Se necesita la ubicación de la solicitud.',
    missingLocalRules: 'Faltan reglas locales de elegibilidad verificadas.',
    exceptions: 'Excepciones relevantes',
    whoQualifies: 'Quién cumple los requisitos',
    geographicRestrictions: 'Restricciones geográficas',
    incomeRequirements: 'Requisitos de ingresos',
    ageHouseholdRequirements: 'Requisitos de edad o del hogar',
    importantExceptions: 'Excepciones importantes',
    applicationDeadline: 'Fecha límite de solicitud',
    documents: 'Documentos requeridos',
    nextSteps: 'Próximos pasos recomendados',
    preliminaryOnly: 'Esta es una evaluación preliminar. La organización toma la decisión final.',
    answerQuestion: 'Pregunta {current} de {total}',
    continue: 'Continuar',
    seeResult: 'Ver resultado',
    restartQuiz: 'Borrar respuestas y comenzar de nuevo',
    noLocalRules: 'No se puede determinar: no hay reglas verificadas para este programa y ubicación.',
    nearbyRulesDiffer: 'Los programas cercanos pueden tener reglas distintas. Este resultado corresponde solo al programa y ubicación indicados.',
    ageRange: 'Rango de edad',
    householdSize: 'Tamaño del hogar',
    incomeRange: 'Rango aproximado de ingresos del hogar',
    housingStatus: 'Situación de vivienda',
    employmentStatus: 'Situación laboral',
    studentStatus: 'Situación estudiantil',
    insuranceStatus: 'Situación de seguro',
    disabilityStatus: 'Situación de discapacidad',
    dependents: 'Número de dependientes',
    programConsiderations: 'Información específica del programa',
    chooseAnswer: 'Elija una respuesta',
    under18: 'Menor de 18',
    age18to24: '18 a 24',
    age25to59: '25 a 59',
    age60plus: '60 años o más',
    incomeUnknown: 'No sabe',
    incomeUnder20: 'Menos de $20,000 al año',
    income20to40: '$20,000–$39,999 al año',
    income40to75: '$40,000–$74,999 al año',
    income75plus: '$75,000 o más al año',
    housed: 'Vivienda estable',
    temporaryHousing: 'Vivienda temporal',
    unhoused: 'Sin vivienda estable',
    employed: 'Con empleo',
    unemployed: 'Sin empleo',
    notWorking: 'No trabaja actualmente',
    student: 'Estudiante',
    notStudent: 'No es estudiante',
    insured: 'Con seguro',
    uninsured: 'Sin seguro',
    disabilityYes: 'Tiene una discapacidad',
    disabilityNo: 'No se indicó una discapacidad',
    requirementsTitle: 'Requisitos locales',
    fullRequirements: 'Revisar todos los requisitos oficiales',
    registrationTitle: 'Ayuda para solicitar',
    registrationProgress: 'Guía de solicitud · paso {current} de {total}',
    registrationStepDocuments: 'Preparar',
    registrationStepApply: 'Solicitar',
    registrationStepConfirm: 'Confirmar',
    registrationNoForm: 'No se encontró una solicitud en línea verificada.',
    registrationUseContact: 'Use la información de contacto verificada para preguntar cómo solicitar.',
    registrationNotRequired: 'Este servicio no requiere inscripción.',
    registrationPhoneOnly: 'La inscripción se realiza por teléfono o en persona.',
    registrationReview: 'Revise la solicitud antes de ingresar información personal.',
    registrationNeverSubmit: 'BridgeAid nunca envía una solicitud externa ni acepta términos por usted.',
    previous: 'Anterior',
    next: 'Siguiente',
    openApplication: 'Abrir solicitud oficial',
    openOfficialSite: 'Abrir sitio oficial',
    applicationProcess: 'Siga estos pasos verificados:',
    waysToApply: 'Formas de solicitar',
    applyThroughLocalProvider: 'A través de un proveedor local',
    applyOnline: 'En línea',
    applyByPhone: 'Por teléfono',
    applyByMail: 'Por correo',
    applyByEmail: 'Por correo electrónico',
    applyByFax: 'Por fax',
    applyInPerson: 'En persona',
    nationwideEyebrow: 'Ayuda disponible en todo Estados Unidos',
    nationwideTitle: 'Ayuda nacional',
    nationwideIntro: 'Use estas herramientas, líneas de ayuda y directorios oficiales verificados sin mezclarlos con los resultados locales cercanos.',
    nationwideFilters: 'Filtrar recursos nacionales en línea',
    nationwideAccess: 'Acceso nacional',
    nationwideAvailability: 'Disponibilidad nacional',
    whoItHelps: 'A quién ayuda',
    onlineEligibilityFilter: 'Elegibilidad',
    applicationMethodFilter: 'Método de solicitud',
    filterAll: 'Todos',
    onlineEligibilityOpen: 'Abierto a todos para información o referencias',
    onlineEligibilityVaries: 'La elegibilidad varía según el programa',
    onlineEligibilityLocalProvider: 'Se aplican las reglas del proveedor local',
    localProviderExplanation: 'Este recurso nacional le conecta con un proveedor local. La sede local establece horarios, documentos, disponibilidad y reglas finales de elegibilidad.',
    openOfficialResource: 'Abrir recurso oficial',
    noOnlineResults: 'Ningún recurso nacional coincide con estos filtros.',
    startApplication: 'Iniciar solicitud',
    completeQuestionnaire: 'Completar cuestionario',
    scheduleAppointment: 'Programar cita',
    downloadApplication: 'Descargar solicitud',
    viewRequiredDocuments: 'Ver documentos requeridos',
    contactIntake: 'Contactar admisión',
    callToApply: 'Llamar para solicitar',
    appointmentRequirements: 'Requisitos de cita',
    callingScript: 'Guion para llamar',
    callingScriptText: 'Hola, llamo por {program}. ¿Podría confirmar quién cumple los requisitos, qué documentos se necesitan y cómo se solicita?',
    helperLocationQuestion: '¿Dónde está la persona que necesita ayuda?',
    helperSupportQuestion: '¿Qué tipos de apoyo está buscando?',
    helperAuthorizedDescription: 'Describa la situación usando solo información que tenga autorización para compartir.',
    helperSupportTypes: 'Seleccione uno o más tipos de apoyo',
    helperSituationLabel: 'Resumen autorizado de la situación',
    helperSituationPlaceholder: 'Incluya límites prácticos, horarios y prioridades, no identificadores sensibles.',
    sharePlan: 'Compartir plan',
    questionsToAsk: 'Preguntas para el proveedor',
    questionsToAskPlaceholder: 'Ejemplo: ¿Hay espacio el martes? ¿Se pueden enviar documentos en línea?',
    confirmedAtRequestedTime: 'Confirmado para {time}',
    unavailableAtRequestedTime: 'No disponible a las {time}',
    uncertainAtRequestedTime: 'La disponibilidad es incierta para {time}',
    whyPrioritized: 'Por qué aparece en esta posición',
    eligibilityResearchPending: 'Investigación de elegibilidad pendiente',
    eligibilityNeedsReview: 'Los detalles de elegibilidad requieren revisión',
    eligibilityOutOfArea: 'El programa no sirve esta ubicación',
    eligibilityResearchPendingExplanation: 'Las fuentes oficiales están en cola para revisión. No es una falla técnica y no se inventaron reglas.',
    eligibilityReviewExplanation: 'Se encontraron fuentes oficiales, pero las reglas son ambiguas y requieren revisión del personal.',
    eligibilityOutOfAreaExplanation: 'El área de servicio verificada no incluye la ubicación ingresada.',
    exportEligibilityCsv: 'Exportar registros de elegibilidad (CSV)',
    eligibilitySourceLink: 'Revisar la fuente oficial de elegibilidad',
    onlineEligibilityStructured: 'Elegibilidad estructurada publicada',
    cost: 'Costo',
    reportTitle: 'Reportar información incorrecta',
    reportIntro: 'Elija lo que parece incorrecto. El reporte se verificará antes de cambiar el recurso.',
    reportType: '¿Qué información es incorrecta?',
    reportAddress: 'Dirección incorrecta',
    reportHours: 'Horario incorrecto',
    reportClosed: 'Programa cerrado',
    reportService: 'El servicio ya no se ofrece',
    reportEligibility: 'Información de elegibilidad incorrecta',
    reportRegistration: 'Enlace de solicitud roto',
    reportDuplicate: 'Recurso duplicado',
    reportOther: 'Otra',
    reportDetails: 'Detalles opcionales',
    reportDetailsPlaceholder: 'Cuente lo que observó sin incluir información personal.',
    submitReport: 'Enviar reporte',
    reportSubmitted: 'El reporte se agregó a la cola de verificación de BridgeAid.',
    reportQueued: 'Pendiente de verificar fuentes',
    reportVerificationProcess: 'BridgeAid comparará el reporte con fuentes oficiales y recientes. Los casos confusos requieren revisión del personal.',
    assistantName: 'BridgeAI',
    assistantSubtitle: 'Basado en recursos guardados y fuentes actuales',
    assistantLoading: 'Consultando la información guardada…',
    assistantSelfOpening: '¿Con qué necesita ayuda ahora?',
    assistantHelperOpening: 'Cuénteme qué necesita la persona y qué limitaciones debemos considerar.',
    chatPlaceholder: 'Pregunte por recursos, horarios, elegibilidad o solicitudes',
    send: 'Enviar',
    assistantNeedLocation: '¿En qué ciudad o código postal debo buscar?',
    assistantNeedNeed: '¿Qué tipo de ayuda necesita?',
    assistantNoVerified: 'No pude verificar un recurso local que coincida. Pruebe otra categoría o llame al 211 para obtener referencias comunitarias.',
    assistantFound: 'Encontré {count} opciones con fuentes cerca de {location}.',
    assistantResourceLine: '{name}. Dirección: {address}. Horario: {hours}. Elegibilidad: {eligibility}. Fuente oficial: {url}',
    assistantHoursUnknown: 'No se pudo verificar el horario. Revise la fuente oficial o contacte al programa antes de ir.',
    assistantHoursKnown: 'Encontré un horario publicado para {program}. A continuación se muestran el estado actual y la semana completa.',
    assistantEligibilityUnknown: 'No se pudieron verificar las reglas locales de elegibilidad para {location}.',
    assistantEligibilityKnown: 'Encontré información de elegibilidad verificada localmente para {program}. Revise los requisitos y confirme con el proveedor.',
    assistantEligibilityNotPublished: '{program} no publica requisitos específicos de elegibilidad. Comuníquese con el proveedor para confirmarlos.',
    assistantLocationKnown: '{program} está en {address}.',
    assistantApplyUnknown: 'No pude verificar una solicitud en línea. Use el teléfono o sitio oficial verificado que aparece en el recurso.',
    footerNotice: 'Confirme horarios, elegibilidad local y pasos de solicitud con la organización.',
    clearDataDone: 'Se borraron los datos locales de BridgeAid.',
    otherNeedRequired: 'Describa el otro tipo de ayuda que necesita.',
    officialSource: 'Fuente oficial',
    typicalLabel: 'Horario habitual; confirme antes de ir',
    unknown: 'Desconocido',
    nonePublished: 'No publicado',
    today: 'Hoy',
    chatLanguageChanged: 'Continuaré en español.'
  }
};

function formatTemplate(template, variables) {
  return String(template).replace(/\{(\w+)(?:,plural,([^,{}]+),([^{}]+))?\}/g, (_, key, one, many) => {
    const value = variables[key] ?? '';
    if (one !== undefined) return Number(value) === 1 ? `${value} ${one}` : `${value} ${many}`;
    return String(value);
  });
}

export function translate(language, key, variables = {}) {
  const locale = SUPPORTED_LANGUAGES.includes(language) ? language : 'en';
  const template = LOCALES[locale][key] ?? LOCALES.en[key] ?? key;
  return formatTemplate(template, variables);
}

export function detectMessageLanguage(message, fallback = 'en') {
  const value = String(message || '').trim();
  if (/[\u3400-\u9fff]/.test(value)) return 'zh';
  if (/[¿¡áéíóúñü]/i.test(value) || /\b(hola|necesito|ayuda|comida|refugio|elegibilidad|solicitar|horario|cerca)\b/i.test(value)) return 'es';
  if (/[A-Za-z]/.test(value)) return 'en';
  return SUPPORTED_LANGUAGES.includes(fallback) ? fallback : 'en';
}

export function requestedLanguage(message) {
  const value = String(message || '').toLowerCase();
  if (/中文|简体|chinese|mandar[ií]n/.test(value)) return 'zh';
  if (/español|spanish|castellano/.test(value)) return 'es';
  if (/english|英文|ingl[eé]s/.test(value)) return 'en';
  return '';
}

export function localeCompleteness() {
  const reference = Object.keys(LOCALES.en);
  return Object.fromEntries(SUPPORTED_LANGUAGES.map(language => [
    language,
    {
      missing: reference.filter(key => !(key in LOCALES[language])),
      extra: Object.keys(LOCALES[language]).filter(key => !reference.includes(key))
    }
  ]));
}
